// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma-next/adapter-mongo/codec-types';
import type { Vector } from '@prisma-next/adapter-mongo/codec-types';

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:50d2aad3ace4b58db948643b4a790cc8b2eb9bfeda129017dc44a04748292bfc'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:840de65fba7eb950a31487f74ee420b9c21205f38bce58579026747e0264e840'>;

export type CodecTypes = MongoCodecTypes;
export type OperationTypes = Record<string, never>;

export type Price = {
  readonly amount: CodecTypes['mongo/double@1']['output'];
  readonly currency: CodecTypes['mongo/string@1']['output'];
};
export type Image = { readonly url: CodecTypes['mongo/string@1']['output'] };
export type Address = {
  readonly streetAndNumber: CodecTypes['mongo/string@1']['output'];
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly postalCode: CodecTypes['mongo/string@1']['output'];
  readonly country: CodecTypes['mongo/string@1']['output'];
};
export type CartItem = {
  readonly productId: CodecTypes['mongo/string@1']['output'];
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly brand: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly price: Price;
  readonly image: Image;
};
export type OrderLineItem = {
  readonly productId: CodecTypes['mongo/string@1']['output'];
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly brand: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly price: Price;
  readonly image: Image;
};
export type StatusEntry = {
  readonly status: CodecTypes['mongo/string@1']['output'];
  readonly timestamp: CodecTypes['mongo/date@1']['output'];
};
export type InvoiceLineItem = {
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly unitPrice: CodecTypes['mongo/double@1']['output'];
  readonly lineTotal: CodecTypes['mongo/double@1']['output'];
};
export type FieldOutputTypes = {
  readonly AddToCartEvent: {
    readonly productId: CodecTypes['mongo/string@1']['output'];
    readonly brand: CodecTypes['mongo/string@1']['output'];
  };
  readonly Cart: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly userId: CodecTypes['mongo/objectId@1']['output'];
    readonly items: ReadonlyArray<CartItem>;
  };
  readonly Event: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly userId: CodecTypes['mongo/string@1']['output'];
    readonly sessionId: CodecTypes['mongo/string@1']['output'];
    readonly type: CodecTypes['mongo/string@1']['output'];
    readonly timestamp: CodecTypes['mongo/date@1']['output'];
  };
  readonly Invoice: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly orderId: CodecTypes['mongo/objectId@1']['output'];
    readonly items: ReadonlyArray<InvoiceLineItem>;
    readonly subtotal: CodecTypes['mongo/double@1']['output'];
    readonly tax: CodecTypes['mongo/double@1']['output'];
    readonly total: CodecTypes['mongo/double@1']['output'];
    readonly issuedAt: CodecTypes['mongo/date@1']['output'];
  };
  readonly Location: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly streetAndNumber: CodecTypes['mongo/string@1']['output'];
    readonly city: CodecTypes['mongo/string@1']['output'];
    readonly postalCode: CodecTypes['mongo/string@1']['output'];
    readonly country: CodecTypes['mongo/string@1']['output'];
  };
  readonly Order: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly userId: CodecTypes['mongo/objectId@1']['output'];
    readonly items: ReadonlyArray<OrderLineItem>;
    readonly shippingAddress: CodecTypes['mongo/string@1']['output'];
    readonly type: CodecTypes['mongo/string@1']['output'];
    readonly statusHistory: ReadonlyArray<StatusEntry>;
  };
  readonly Product: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly brand: CodecTypes['mongo/string@1']['output'];
    readonly code: CodecTypes['mongo/string@1']['output'];
    readonly description: CodecTypes['mongo/string@1']['output'];
    readonly masterCategory: CodecTypes['mongo/string@1']['output'];
    readonly subCategory: CodecTypes['mongo/string@1']['output'];
    readonly articleType: CodecTypes['mongo/string@1']['output'];
    readonly price: Price;
    readonly image: Image;
    readonly embedding: ReadonlyArray<CodecTypes['mongo/double@1']['output']> | null;
  };
  readonly SearchEvent: { readonly query: CodecTypes['mongo/string@1']['output'] };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
    readonly address: Address | null;
  };
  readonly ViewProductEvent: {
    readonly productId: CodecTypes['mongo/string@1']['output'];
    readonly subCategory: CodecTypes['mongo/string@1']['output'];
    readonly brand: CodecTypes['mongo/string@1']['output'];
    readonly exitMethod: CodecTypes['mongo/string@1']['output'] | null;
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes, FieldOutputTypes>;

type ContractBase = ContractType<
  {
    readonly collections: {
      readonly products: Record<string, never>;
      readonly users: {
        readonly indexes: readonly [
          { readonly fields: { readonly email: 1 }; readonly options: { readonly unique: true } },
        ];
      };
      readonly carts: { readonly indexes: readonly [{ readonly fields: { readonly userId: 1 } }] };
      readonly orders: { readonly indexes: readonly [{ readonly fields: { readonly userId: 1 } }] };
      readonly locations: Record<string, never>;
      readonly invoices: Record<string, never>;
      readonly events: { readonly indexes: readonly [{ readonly fields: { readonly userId: 1 } }] };
      readonly viewProductEvent: Record<string, never>;
      readonly searchEvent: Record<string, never>;
      readonly addToCartEvent: Record<string, never>;
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly AddToCartEvent: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly base: 'Event';
    };
    readonly Cart: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly items: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'CartItem' };
          readonly many: true;
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'carts' };
    };
    readonly Event: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly sessionId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly type: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly timestamp: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly discriminator: { readonly field: 'type' };
      readonly variants: {
        readonly ViewProductEvent: { readonly value: 'view-product' };
        readonly SearchEvent: { readonly value: 'search' };
        readonly AddToCartEvent: { readonly value: 'add-to-cart' };
      };
    };
    readonly Invoice: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly orderId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly items: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'InvoiceLineItem' };
          readonly many: true;
        };
        readonly subtotal: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly tax: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly total: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly issuedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: {
        readonly order: {
          readonly to: 'Order';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['orderId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'invoices' };
    };
    readonly Location: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly streetAndNumber: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'locations' };
    };
    readonly Order: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly items: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'OrderLineItem' };
          readonly many: true;
        };
        readonly shippingAddress: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly type: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly statusHistory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'StatusEntry' };
          readonly many: true;
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['_id'];
          };
        };
        readonly invoices: {
          readonly to: 'Invoice';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['orderId'];
          };
        };
      };
      readonly storage: { readonly collection: 'orders' };
    };
    readonly Product: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly code: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly description: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly masterCategory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly subCategory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly articleType: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
        readonly embedding: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
          readonly many: true;
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'products' };
    };
    readonly SearchEvent: {
      readonly fields: {
        readonly query: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly base: 'Event';
    };
    readonly User: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly address: {
          readonly nullable: true;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
        };
      };
      readonly relations: {
        readonly carts: {
          readonly to: 'Cart';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['userId'];
          };
        };
        readonly orders: {
          readonly to: 'Order';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['userId'];
          };
        };
      };
      readonly storage: { readonly collection: 'users' };
    };
    readonly ViewProductEvent: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly subCategory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly exitMethod: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly base: 'Event';
    };
  }
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly products: 'Product';
    readonly users: 'User';
    readonly carts: 'Cart';
    readonly orders: 'Order';
    readonly locations: 'Location';
    readonly invoices: 'Invoice';
    readonly events: 'Event';
  };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Price: {
      readonly fields: {
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly currency: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly Image: {
      readonly fields: {
        readonly url: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly Address: {
      readonly fields: {
        readonly streetAndNumber: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly CartItem: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
      };
    };
    readonly OrderLineItem: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
      };
    };
    readonly StatusEntry: {
      readonly fields: {
        readonly status: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly timestamp: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
    };
    readonly InvoiceLineItem: {
      readonly fields: {
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly unitPrice: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly lineTotal: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
