// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma-next/adapter-mongo/codec-types';
import type { Vector } from '@prisma-next/adapter-mongo/codec-types';

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:75b661bfd9821fea5cf1d87c416de45ea331e58ba65787c853bb1ee3642fa116'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:840de65fba7eb950a31487f74ee420b9c21205f38bce58579026747e0264e840'>;

export type CodecTypes = MongoCodecTypes;
export type OperationTypes = Record<string, never>;

export type AddressOutput = {
  readonly street: CodecTypes['mongo/string@1']['output'];
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly zip: CodecTypes['mongo/string@1']['output'] | null;
  readonly country: CodecTypes['mongo/string@1']['output'];
};
export type AddressInput = {
  readonly street: CodecTypes['mongo/string@1']['input'];
  readonly city: CodecTypes['mongo/string@1']['input'];
  readonly zip: CodecTypes['mongo/string@1']['input'] | null;
  readonly country: CodecTypes['mongo/string@1']['input'];
};
export type FieldOutputTypes = {
  readonly Article: { readonly summary: CodecTypes['mongo/string@1']['output'] };
  readonly Post: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly title: CodecTypes['mongo/string@1']['output'];
    readonly content: CodecTypes['mongo/string@1']['output'];
    readonly kind: CodecTypes['mongo/string@1']['output'];
    readonly authorId: CodecTypes['mongo/objectId@1']['output'];
    readonly createdAt: CodecTypes['mongo/date@1']['output'];
  };
  readonly Tutorial: {
    readonly difficulty: CodecTypes['mongo/string@1']['output'];
    readonly duration: CodecTypes['mongo/int32@1']['output'];
  };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
    readonly bio: CodecTypes['mongo/string@1']['output'] | null;
    readonly address: AddressOutput | null;
  };
};
export type FieldInputTypes = {
  readonly Article: { readonly summary: CodecTypes['mongo/string@1']['input'] };
  readonly Post: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly title: CodecTypes['mongo/string@1']['input'];
    readonly content: CodecTypes['mongo/string@1']['input'];
    readonly kind: CodecTypes['mongo/string@1']['input'];
    readonly authorId: CodecTypes['mongo/objectId@1']['input'];
    readonly createdAt: CodecTypes['mongo/date@1']['input'];
  };
  readonly Tutorial: {
    readonly difficulty: CodecTypes['mongo/string@1']['input'];
    readonly duration: CodecTypes['mongo/int32@1']['input'];
  };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly name: CodecTypes['mongo/string@1']['input'];
    readonly email: CodecTypes['mongo/string@1']['input'];
    readonly bio: CodecTypes['mongo/string@1']['input'] | null;
    readonly address: AddressInput | null;
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly collections: {
      readonly users: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly name: { readonly bsonType: 'string' };
              readonly email: { readonly bsonType: 'string' };
              readonly bio: { readonly bsonType: readonly ['null', 'string'] };
              readonly address: {
                readonly oneOf: readonly [
                  { readonly bsonType: 'null' },
                  {
                    readonly bsonType: 'object';
                    readonly properties: {
                      readonly street: { readonly bsonType: 'string' };
                      readonly city: { readonly bsonType: 'string' };
                      readonly zip: { readonly bsonType: readonly ['null', 'string'] };
                      readonly country: { readonly bsonType: 'string' };
                    };
                    readonly required: readonly ['city', 'country', 'street'];
                  },
                ];
              };
            };
            readonly required: readonly ['_id', 'email', 'name'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly posts: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly title: { readonly bsonType: 'string' };
              readonly content: { readonly bsonType: 'string' };
              readonly kind: { readonly bsonType: 'string' };
              readonly authorId: { readonly bsonType: 'objectId' };
              readonly createdAt: { readonly bsonType: 'date' };
            };
            readonly required: readonly [
              '_id',
              'authorId',
              'content',
              'createdAt',
              'kind',
              'title',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly article: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: { readonly summary: { readonly bsonType: 'string' } };
            readonly required: readonly ['summary'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly tutorial: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly difficulty: { readonly bsonType: 'string' };
              readonly duration: { readonly bsonType: 'int' };
            };
            readonly required: readonly ['difficulty', 'duration'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Article: {
      readonly fields: {
        readonly summary: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'posts' };
      readonly base: 'Post';
    };
    readonly Post: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly content: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly kind: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: {
        readonly author: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['authorId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'posts' };
      readonly discriminator: { readonly field: 'kind' };
      readonly variants: {
        readonly Article: { readonly value: 'article' };
        readonly Tutorial: { readonly value: 'tutorial' };
      };
    };
    readonly Tutorial: {
      readonly fields: {
        readonly difficulty: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly duration: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'posts' };
      readonly base: 'Post';
    };
    readonly User: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly bio: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly address: {
          readonly nullable: true;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: 'Post';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['authorId'];
          };
        };
      };
      readonly storage: { readonly collection: 'users' };
    };
  }
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: { readonly users: 'User'; readonly posts: 'Post' };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Address: {
      readonly fields: {
        readonly street: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly zip: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
