// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';
import type { CodecTypes as SqliteVectorTypes } from '@prisma-next/extension-sqlite-vector/codec-types';
import type { Vector } from '@prisma-next/extension-sqlite-vector/codec-types';
import type { OperationTypes as SqliteVectorOperationTypes } from '@prisma-next/extension-sqlite-vector/operation-types';

import type { CoreHashBase, ProfileHashBase } from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type CoreHash =
  CoreHashBase<'sha256:470f2b3ae9a5f47c9ddda58fff0406d5cbac59bb09770c2e00b33c2502897820'>;
export type ProfileHash =
  ProfileHashBase<'sha256:e668a0ecff98e7aa08a807ae2cf547b997002d8a6e0d5b7741d2df62116d6de7'>;

export type CodecTypes = SqliteTypes & SqliteVectorTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = SqliteVectorOperationTypes;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly user: {
        columns: {
          readonly id: {
            readonly nativeType: 'integer';
            readonly codecId: 'sqlite/int@1';
            readonly nullable: false;
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/datetime@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly post: {
        columns: {
          readonly id: {
            readonly nativeType: 'integer';
            readonly codecId: 'sqlite/int@1';
            readonly nullable: false;
          };
          readonly title: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly userId: {
            readonly nativeType: 'integer';
            readonly codecId: 'sqlite/int@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/datetime@1';
            readonly nullable: false;
          };
          readonly embedding: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/vector@1';
            readonly nullable: true;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['userId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly name: 'post_userId_fkey';
          },
        ];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly User: {
      storage: { readonly table: 'user' };
      fields: {
        readonly id: CodecTypes['sqlite/int@1']['output'];
        readonly email: CodecTypes['sqlite/text@1']['output'];
        readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      };
    };
    readonly Post: {
      storage: { readonly table: 'post' };
      fields: {
        readonly id: CodecTypes['sqlite/int@1']['output'];
        readonly title: CodecTypes['sqlite/text@1']['output'];
        readonly userId: CodecTypes['sqlite/int@1']['output'];
        readonly embedding: CodecTypes['sqlite/vector@1']['output'] | null;
        readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
      };
    };
  },
  {
    readonly user: {
      readonly posts: {
        readonly to: 'Post';
        readonly cardinality: '1:N';
        readonly on: {
          readonly parentCols: readonly ['id'];
          readonly childCols: readonly ['userId'];
        };
      };
    };
    readonly post: {
      readonly user: {
        readonly to: 'User';
        readonly cardinality: 'N:1';
        readonly on: {
          readonly parentCols: readonly ['userId'];
          readonly childCols: readonly ['id'];
        };
      };
    };
  },
  {
    modelToTable: { readonly User: 'user'; readonly Post: 'post' };
    tableToModel: { readonly user: 'User'; readonly post: 'Post' };
    fieldToColumn: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly createdAt: 'createdAt';
      };
      readonly Post: {
        readonly id: 'id';
        readonly title: 'title';
        readonly userId: 'userId';
        readonly embedding: 'embedding';
        readonly createdAt: 'createdAt';
      };
    };
    columnToField: {
      readonly user: {
        readonly id: 'id';
        readonly email: 'email';
        readonly createdAt: 'createdAt';
      };
      readonly post: {
        readonly id: 'id';
        readonly title: 'title';
        readonly userId: 'userId';
        readonly embedding: 'embedding';
        readonly createdAt: 'createdAt';
      };
    };
    codecTypes: SqliteTypes & SqliteVectorTypes;
    operationTypes: SqliteVectorOperationTypes;
  },
  CoreHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
