// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:357b86d293f0fd09eead75c96d2665e3c5fa463c584353411e74cfd160f45116'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:0903547be862dca3fa2dbc62a85cd52e9ca595f00cf43b6b26a3da3d4b9740ae'>;
export type ProfileHash =
  ProfileHashBase<'sha256:213031a5ce861b455f22bc065769080ea0357fabcb999de0190524ecd32531f7'>;

export type CodecTypes = SqliteTypes;
export type OperationTypes = Record<string, never>;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Post: {
    readonly id: CodecTypes['sql/char@1']['output'];
    readonly title: CodecTypes['sqlite/text@1']['output'];
    readonly userId: CodecTypes['sql/char@1']['output'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
  };
  readonly User: {
    readonly id: CodecTypes['sql/char@1']['output'];
    readonly email: CodecTypes['sqlite/text@1']['output'];
    readonly displayName: CodecTypes['sqlite/text@1']['output'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['output'];
    readonly kind: CodecTypes['sqlite/text@1']['output'];
    readonly address: CodecTypes['sqlite/json@1']['output'] | null;
  };
};
export type FieldInputTypes = {
  readonly Post: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly title: CodecTypes['sqlite/text@1']['input'];
    readonly userId: CodecTypes['sql/char@1']['input'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
  };
  readonly User: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly email: CodecTypes['sqlite/text@1']['input'];
    readonly displayName: CodecTypes['sqlite/text@1']['input'];
    readonly createdAt: CodecTypes['sqlite/datetime@1']['input'];
    readonly kind: CodecTypes['sqlite/text@1']['input'];
    readonly address: CodecTypes['sqlite/json@1']['input'] | null;
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  OperationTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly tables: {
      readonly post: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly title: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly userId: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly createdAt: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/datetime@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['userId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly name: 'post_userId_fkey';
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly user: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly displayName: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/datetime@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly kind: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/text@1';
            readonly nullable: false;
          };
          readonly address: {
            readonly nativeType: 'text';
            readonly codecId: 'sqlite/json@1';
            readonly nullable: true;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
    readonly storageHash: StorageHash;
  },
  {
    readonly Post: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['id'];
          };
        };
      };
      readonly storage: {
        readonly table: 'post';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly title: { readonly column: 'title' };
          readonly userId: { readonly column: 'userId' };
          readonly createdAt: { readonly column: 'createdAt' };
        };
      };
    };
    readonly User: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly displayName: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/datetime@1' };
        };
        readonly kind: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
        };
        readonly address: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/json@1' };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: 'Post';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['userId'];
          };
        };
      };
      readonly storage: {
        readonly table: 'user';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly email: { readonly column: 'email' };
          readonly displayName: { readonly column: 'displayName' };
          readonly createdAt: { readonly column: 'createdAt' };
          readonly kind: { readonly column: 'kind' };
          readonly address: { readonly column: 'address' };
        };
      };
    };
  }
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: { readonly user: 'User'; readonly post: 'Post' };
  readonly capabilities: {
    readonly sql: {
      readonly autoIndexesForeignKeys: false;
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'post'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'user'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
