// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';

import type { CoreHashBase, ProfileHashBase } from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type CoreHash =
  CoreHashBase<'sha256:ddc7ae4652bb5dec24056f58ebef47228f06948cffc0d394661d83aa3a82da7d'>;
export type ProfileHash =
  ProfileHashBase<'sha256:13a235d20f545252b6ae3d59951cebc566729bd4a3241dc092aa7f58f55a42c4'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly User: {
        columns: {
          readonly id: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly User: {
      storage: { readonly table: 'User' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly email: CodecTypes['pg/text@1']['output'];
        readonly name: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: { readonly User: 'User' };
    tableToModel: { readonly User: 'User' };
    fieldToColumn: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly name: 'name';
        readonly createdAt: 'createdAt';
      };
    };
    columnToField: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly name: 'name';
        readonly createdAt: 'createdAt';
      };
    };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  },
  CoreHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
