// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next emit'.
// To regenerate, run: prisma-next emit --contract <path> --out <dir>
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';

import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-target';

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly User: {
        columns: {
          readonly id: { readonly type: 'pg/text@1'; readonly nullable: false };
          readonly email: { readonly type: 'pg/text@1'; readonly nullable: false };
          readonly name: { readonly type: 'pg/text@1'; readonly nullable: false };
          readonly createdAt: { readonly type: 'pg/timestamptz@1'; readonly nullable: false };
        };
        primaryKey: { readonly columns: readonly ['id'] };
      };
    };
  },
  {
    readonly User: {
      storage: { readonly table: 'User' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly email: CodecTypes['pg/text@1']['output'];
        readonly name: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: { readonly User: 'User' };
    tableToModel: { readonly User: 'User' };
    fieldToColumn: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly name: 'name';
        readonly createdAt: 'createdAt';
      };
    };
    columnToField: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly name: 'name';
        readonly createdAt: 'createdAt';
      };
    };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  }
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
