// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';

import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';
import type {
  ContractWithTypeMaps,
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type StorageHash =
  StorageHashBase<'sha256:9f80f039119cc3f48a19da5d3517ae892c168790944aefffea9988e9b09625ae'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:13a235d20f545252b6ae3d59951cebc566729bd4a3241dc092aa7f58f55a42c4'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;

export type TypeMaps = {
  readonly codecTypes: CodecTypes;
  readonly operationTypes: OperationTypes;
};

export type Contract = ContractWithTypeMaps<SqlContract<
  {
    readonly tables: {
      readonly User: {
        columns: {
          readonly id: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly User: {
      storage: { readonly table: 'User' };
      fields: {
        readonly id: CodecTypes['pg/text@1']['output'];
        readonly email: CodecTypes['pg/text@1']['output'];
        readonly name: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: { readonly User: 'User' };
    tableToModel: { readonly User: 'User' };
    fieldToColumn: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly name: 'name';
        readonly createdAt: 'createdAt';
      };
    };
    columnToField: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly name: 'name';
        readonly createdAt: 'createdAt';
      };
    };
  },
  StorageHash,
  ExecutionHash,
  ProfileHash
>, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
