// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/target-postgres/codec-types';
import type { JsonValue } from '@prisma-next/target-postgres/codec-types';
import type { Char } from '@prisma-next/target-postgres/codec-types';
import type { Varchar } from '@prisma-next/target-postgres/codec-types';
import type { Numeric } from '@prisma-next/target-postgres/codec-types';
import type { Bit } from '@prisma-next/target-postgres/codec-types';
import type { VarBit } from '@prisma-next/target-postgres/codec-types';
import type { Timestamp } from '@prisma-next/target-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/target-postgres/codec-types';
import type { Time } from '@prisma-next/target-postgres/codec-types';
import type { Timetz } from '@prisma-next/target-postgres/codec-types';
import type { Interval } from '@prisma-next/target-postgres/codec-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:107ce92788984cad3aff9ee860e328048f14e156869ae418ba9ec96f31d6f4df'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly FeatureFlag: {
    readonly key: CodecTypes['pg/text@1']['output'];
    readonly enabled: CodecTypes['pg/bool@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly FeatureFlag: {
    readonly key: CodecTypes['pg/text@1']['input'];
    readonly enabled: CodecTypes['pg/bool@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly tables: {
      readonly feature_flag: {
        columns: {
          readonly key: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly enabled: {
            readonly nativeType: 'bool';
            readonly codecId: 'pg/bool@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['key'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
    readonly storageHash: StorageHash;
  },
  {
    readonly FeatureFlag: {
      readonly fields: {
        readonly key: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly enabled: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'feature_flag';
        readonly fields: {
          readonly key: { readonly column: 'key' };
          readonly enabled: { readonly column: 'enabled' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: { readonly feature_flag: 'FeatureFlag' };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
