packages:
  - packages/**
  - examples/*
  - test/**
  - '!**/dist-*'

allowBuilds:
  '@prisma/client@6.18.0': true
  '@prisma/engines@6.18.0': true
  esbuild@0.25.11 || 0.27.2: true
  prisma@6.18.0: true

blockExoticSubdeps: true

catalog:
  '@prisma/dev': 0.19.1
  '@types/node': 24.10.4
  '@types/pg': 8.16.0
  gray-matter: ^4.0.3
  pg: 8.16.3
  tsdown: 0.18.4
  tsup: 8.5.1
  typescript: 5.9.3
  vitest: 4.0.16

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
