import type { ContractIR } from '@prisma-next/contract/ir';
import type { TargetFamilyHook, ValidationContext } from '@prisma-next/contract/types';
import { ifDefined } from '@prisma-next/utils/defined';
import { type } from 'arktype';
import { format } from 'prettier';
import { canonicalizeContract } from './canonicalization';
import { computeExecutionHash, computeProfileHash, computeStorageHash } from './hashing';
import type { EmitOptions, EmitResult } from './types';

const CanonicalMetaSchema = type({
  '[string]': 'unknown',
});

const CanonicalContractSchema = type({
  '+': 'reject',
  schemaVersion: 'string',
  targetFamily: 'string',
  target: 'string',
  models: type({ '[string]': 'unknown' }),
  relations: type({ '[string]': 'unknown' }),
  storage: type({ '[string]': 'unknown' }),
  'execution?': type({ '[string]': 'unknown' }),
  extensionPacks: type({ '[string]': 'unknown' }),
  capabilities: type({
    '[string]': type({
      '[string]': 'boolean',
    }),
  }),
  meta: CanonicalMetaSchema,
});

function assertCanonicalArtifactShape(value: unknown): void {
  const result = CanonicalContractSchema(value);
  if (result instanceof type.errors) {
    const issues = result
      .map((error) => {
        const path = error.path?.toString() ?? '<root>';
        return `${path}: ${error.message}`;
      })
      .join('; ');
    throw new Error(`ContractIR canonical artifact validation failed: ${issues}`);
  }
}

function validateCoreStructure(ir: ContractIR): void {
  if (!ir.targetFamily) {
    throw new Error('ContractIR must have targetFamily');
  }
  if (!ir.target) {
    throw new Error('ContractIR must have target');
  }
  if (!ir.schemaVersion) {
    throw new Error('ContractIR must have schemaVersion');
  }
  if (!ir.models || typeof ir.models !== 'object') {
    throw new Error('ContractIR must have models');
  }
  if (!ir.storage || typeof ir.storage !== 'object') {
    throw new Error('ContractIR must have storage');
  }
  if (!ir.relations || typeof ir.relations !== 'object') {
    throw new Error('ContractIR must have relations');
  }
  if (!ir.extensionPacks || typeof ir.extensionPacks !== 'object') {
    throw new Error('ContractIR must have extensionPacks');
  }
  if (!ir.capabilities || typeof ir.capabilities !== 'object') {
    throw new Error('ContractIR must have capabilities');
  }
  if (!ir.meta || typeof ir.meta !== 'object') {
    throw new Error('ContractIR must have meta');
  }
}

export async function emit(
  ir: ContractIR,
  options: EmitOptions,
  targetFamily: TargetFamilyHook,
): Promise<EmitResult> {
  const {
    operationRegistry,
    codecTypeImports,
    operationTypeImports,
    extensionIds,
    parameterizedRenderers,
    parameterizedTypeImports,
  } = options;

  validateCoreStructure(ir);

  const ctx: ValidationContext = {
    ...ifDefined('operationRegistry', operationRegistry),
    ...ifDefined('codecTypeImports', codecTypeImports),
    ...ifDefined('operationTypeImports', operationTypeImports),
    ...ifDefined('extensionIds', extensionIds),
  };
  targetFamily.validateTypes(ir, ctx);

  targetFamily.validateStructure(ir);

  const canonicalContract = {
    schemaVersion: ir.schemaVersion,
    targetFamily: ir.targetFamily,
    target: ir.target,
    models: ir.models,
    relations: ir.relations,
    storage: ir.storage,
    ...ifDefined('execution', ir.execution),
    extensionPacks: ir.extensionPacks,
    capabilities: ir.capabilities,
    meta: ir.meta,
  };
  assertCanonicalArtifactShape(canonicalContract);

  const storageHash = computeStorageHash(canonicalContract);
  const executionHash = canonicalContract.execution
    ? computeExecutionHash(canonicalContract)
    : undefined;
  const profileHash = computeProfileHash(canonicalContract);

  const contractWithHashes = {
    ...canonicalContract,
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };

  // Add _generated metadata to indicate this is a generated artifact
  // This ensures consistency between CLI emit and programmatic emit
  // Always add/update _generated with standard content for consistency
  const contractJsonObj = JSON.parse(
    canonicalizeContract(
      contractWithHashes as ContractIR & {
        storageHash?: string;
        executionHash?: string;
        profileHash?: string;
      },
    ),
  ) as Record<string, unknown>;
  const contractJsonWithMeta = {
    ...contractJsonObj,
    _generated: {
      warning: '⚠️  GENERATED FILE - DO NOT EDIT',
      message: 'This file is automatically generated by "prisma-next contract emit".',
      regenerate: 'To regenerate, run: prisma-next contract emit',
    },
  };
  const contractJsonString = JSON.stringify(contractJsonWithMeta, null, 2);

  const generateOptions =
    parameterizedRenderers || parameterizedTypeImports
      ? {
          ...ifDefined('parameterizedRenderers', parameterizedRenderers),
          ...ifDefined('parameterizedTypeImports', parameterizedTypeImports),
        }
      : undefined;

  const contractTypeHashes = {
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };
  const contractDtsRaw = targetFamily.generateContractTypes(
    ir,
    codecTypeImports ?? [],
    operationTypeImports ?? [],
    contractTypeHashes,
    generateOptions,
  );
  const contractDts = await format(contractDtsRaw, {
    parser: 'typescript',
    singleQuote: true,
    semi: true,
    printWidth: 100,
  });

  return {
    contractJson: contractJsonString,
    contractDts,
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };
}
