import type { ContractIR } from '@prisma-next/contract/ir';
import type { TargetFamilyHook, ValidationContext } from '@prisma-next/contract/types';
import { ifDefined } from '@prisma-next/utils/defined';
import { format } from 'prettier';
import { canonicalizeContract } from './canonicalization';
import { computeExecutionHash, computeProfileHash, computeStorageHash } from './hashing';
import type { EmitOptions, EmitResult } from './types';

const PROVENANCE_KEYS = new Set(['source', 'sourceId', 'schemaPath', 'sources']);

function stripProvenance(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => stripProvenance(entry));
  }
  if (!value || typeof value !== 'object') {
    return value;
  }

  const sanitized: Record<string, unknown> = {};
  for (const [key, entry] of Object.entries(value)) {
    if (PROVENANCE_KEYS.has(key)) {
      continue;
    }
    sanitized[key] = stripProvenance(entry);
  }
  return sanitized;
}

function validateCoreStructure(ir: ContractIR): void {
  if (!ir.targetFamily) {
    throw new Error('ContractIR must have targetFamily');
  }
  if (!ir.target) {
    throw new Error('ContractIR must have target');
  }
  if (!ir.schemaVersion) {
    throw new Error('ContractIR must have schemaVersion');
  }
  if (!ir.models || typeof ir.models !== 'object') {
    throw new Error('ContractIR must have models');
  }
  if (!ir.storage || typeof ir.storage !== 'object') {
    throw new Error('ContractIR must have storage');
  }
  if (!ir.relations || typeof ir.relations !== 'object') {
    throw new Error('ContractIR must have relations');
  }
  if (!ir.extensionPacks || typeof ir.extensionPacks !== 'object') {
    throw new Error('ContractIR must have extensionPacks');
  }
  if (!ir.capabilities || typeof ir.capabilities !== 'object') {
    throw new Error('ContractIR must have capabilities');
  }
  if (!ir.meta || typeof ir.meta !== 'object') {
    throw new Error('ContractIR must have meta');
  }
}

export async function emit(
  ir: ContractIR,
  options: EmitOptions,
  targetFamily: TargetFamilyHook,
): Promise<EmitResult> {
  const {
    operationRegistry,
    codecTypeImports,
    operationTypeImports,
    extensionIds,
    parameterizedRenderers,
    parameterizedTypeImports,
  } = options;

  validateCoreStructure(ir);

  const ctx: ValidationContext = {
    ...ifDefined('operationRegistry', operationRegistry),
    ...ifDefined('codecTypeImports', codecTypeImports),
    ...ifDefined('operationTypeImports', operationTypeImports),
    ...ifDefined('extensionIds', extensionIds),
  };
  targetFamily.validateTypes(ir, ctx);

  targetFamily.validateStructure(ir);

  const contractJson = {
    schemaVersion: ir.schemaVersion,
    targetFamily: ir.targetFamily,
    target: ir.target,
    models: ir.models,
    relations: ir.relations,
    storage: ir.storage,
    ...ifDefined('execution', ir.execution),
    extensionPacks: ir.extensionPacks,
    capabilities: ir.capabilities,
    meta: stripProvenance(ir.meta) as Record<string, unknown>,
  } as const;

  const storageHash = computeStorageHash(contractJson);
  const executionHash = ir.execution ? computeExecutionHash(contractJson) : undefined;
  const profileHash = computeProfileHash(contractJson);

  const contractWithHashes: ContractIR & {
    storageHash?: string;
    executionHash?: string;
    profileHash?: string;
  } = {
    ...ir,
    meta: stripProvenance(ir.meta) as Record<string, unknown>,
    schemaVersion: contractJson.schemaVersion,
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };

  // Add _generated metadata to indicate this is a generated artifact
  // This ensures consistency between CLI emit and programmatic emit
  // Always add/update _generated with standard content for consistency
  const contractJsonObj = JSON.parse(canonicalizeContract(contractWithHashes)) as Record<
    string,
    unknown
  >;
  const contractJsonWithMeta = {
    ...contractJsonObj,
    _generated: {
      warning: '⚠️  GENERATED FILE - DO NOT EDIT',
      message: 'This file is automatically generated by "prisma-next contract emit".',
      regenerate: 'To regenerate, run: prisma-next contract emit',
    },
  };
  const contractJsonString = JSON.stringify(contractJsonWithMeta, null, 2);

  const generateOptions =
    parameterizedRenderers || parameterizedTypeImports
      ? {
          ...ifDefined('parameterizedRenderers', parameterizedRenderers),
          ...ifDefined('parameterizedTypeImports', parameterizedTypeImports),
        }
      : undefined;

  const contractTypeHashes = {
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };
  const contractDtsRaw = targetFamily.generateContractTypes(
    ir,
    codecTypeImports ?? [],
    operationTypeImports ?? [],
    contractTypeHashes,
    generateOptions,
  );
  const contractDts = await format(contractDtsRaw, {
    parser: 'typescript',
    singleQuote: true,
    semi: true,
    printWidth: 100,
  });

  return {
    contractJson: contractJsonString,
    contractDts,
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };
}
