import type { ContractIR } from '@prisma-next/contract/ir';
import type { TargetFamilyHook, ValidationContext } from '@prisma-next/contract/types';
import { format } from 'prettier';
import { canonicalizeContract } from './canonicalization';
import { computeCoreHash, computeProfileHash } from './hashing';
import type { EmitOptions, EmitResult } from './types';

function validateCoreStructure(ir: ContractIR): void {
  if (!ir.targetFamily) {
    throw new Error('ContractIR must have targetFamily');
  }
  if (!ir.target) {
    throw new Error('ContractIR must have target');
  }
  if (!ir.schemaVersion) {
    throw new Error('ContractIR must have schemaVersion');
  }
  if (!ir.models || typeof ir.models !== 'object') {
    throw new Error('ContractIR must have models');
  }
  if (!ir.storage || typeof ir.storage !== 'object') {
    throw new Error('ContractIR must have storage');
  }
  if (!ir.relations || typeof ir.relations !== 'object') {
    throw new Error('ContractIR must have relations');
  }
  if (!ir.extensions || typeof ir.extensions !== 'object') {
    throw new Error('ContractIR must have extensions');
  }
  if (!ir.capabilities || typeof ir.capabilities !== 'object') {
    throw new Error('ContractIR must have capabilities');
  }
  if (!ir.meta || typeof ir.meta !== 'object') {
    throw new Error('ContractIR must have meta');
  }
  if (!ir.sources || typeof ir.sources !== 'object') {
    throw new Error('ContractIR must have sources');
  }
}

export async function emit(
  ir: ContractIR,
  options: EmitOptions,
  targetFamily: TargetFamilyHook,
): Promise<EmitResult> {
  const { operationRegistry, codecTypeImports, operationTypeImports, extensionIds } = options;

  validateCoreStructure(ir);

  const ctx: ValidationContext = {
    ...(operationRegistry ? { operationRegistry } : {}),
    ...(codecTypeImports ? { codecTypeImports } : {}),
    ...(operationTypeImports ? { operationTypeImports } : {}),
    ...(extensionIds ? { extensionIds } : {}),
  };
  targetFamily.validateTypes(ir, ctx);

  targetFamily.validateStructure(ir);

  const contractJson = {
    schemaVersion: ir.schemaVersion,
    targetFamily: ir.targetFamily,
    target: ir.target,
    models: ir.models,
    relations: ir.relations,
    storage: ir.storage,
    extensions: ir.extensions,
    capabilities: ir.capabilities,
    meta: ir.meta,
    sources: ir.sources,
  } as const;

  const coreHash = computeCoreHash(contractJson);
  const profileHash = computeProfileHash(contractJson);

  const contractWithHashes: ContractIR & { coreHash?: string; profileHash?: string } = {
    ...ir,
    schemaVersion: contractJson.schemaVersion,
    coreHash,
    profileHash,
  };

  // Add _generated metadata to indicate this is a generated artifact
  // This ensures consistency between CLI emit and programmatic emit
  // Always add/update _generated with standard content for consistency
  const contractJsonObj = JSON.parse(canonicalizeContract(contractWithHashes)) as Record<
    string,
    unknown
  >;
  const contractJsonWithMeta = {
    ...contractJsonObj,
    _generated: {
      warning: '⚠️  GENERATED FILE - DO NOT EDIT',
      message: 'This file is automatically generated by "prisma-next emit".',
      regenerate: 'To regenerate, run: prisma-next emit',
    },
  };
  const contractJsonString = JSON.stringify(contractJsonWithMeta, null, 2);

  const contractDtsRaw = targetFamily.generateContractTypes(
    ir,
    codecTypeImports ?? [],
    operationTypeImports ?? [],
  );
  const contractDts = await format(contractDtsRaw, {
    parser: 'typescript',
    singleQuote: true,
    semi: true,
    printWidth: 100,
  });

  return {
    contractJson: contractJsonString,
    contractDts,
    coreHash,
    profileHash,
  };
}
