// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/target-postgres/codec-types';
import type { JsonValue } from '@prisma-next/target-postgres/codec-types';
import type { Char } from '@prisma-next/target-postgres/codec-types';
import type { Varchar } from '@prisma-next/target-postgres/codec-types';
import type { Numeric } from '@prisma-next/target-postgres/codec-types';
import type { Bit } from '@prisma-next/target-postgres/codec-types';
import type { VarBit } from '@prisma-next/target-postgres/codec-types';
import type { Timestamp } from '@prisma-next/target-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/target-postgres/codec-types';
import type { Time } from '@prisma-next/target-postgres/codec-types';
import type { Timetz } from '@prisma-next/target-postgres/codec-types';
import type { Interval } from '@prisma-next/target-postgres/codec-types';
import type { CodecTypes as PostgisTypes } from '@prisma-next/extension-postgis/codec-types';
import type { Geometry } from '@prisma-next/extension-postgis/codec-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type { QueryOperationTypes as PostgisQueryOperationTypes } from '@prisma-next/extension-postgis/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:6a2f3764720ac636d1d9bb48f2fbb00d6429d26498a168deb58ca6c9b1cb1d11'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:815d2a9f2f35488d3bb0aeba687849e2475b621c331c1d27ad79e37b6e56182f'>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes & PostgisTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  PostgisQueryOperationTypes<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Cafe: {
    readonly id: Char<36>;
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly location: Geometry<4326>;
  };
  readonly Neighborhood: {
    readonly id: Char<36>;
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly boundary: Geometry<4326>;
  };
  readonly Route: {
    readonly id: Char<36>;
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly path: Geometry<4326>;
  };
};
export type FieldInputTypes = {
  readonly Cafe: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly location: CodecTypes['pg/geometry@1']['input'];
  };
  readonly Neighborhood: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly boundary: CodecTypes['pg/geometry@1']['input'];
  };
  readonly Route: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly path: CodecTypes['pg/geometry@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly tables: {
      readonly cafe: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly location: {
            readonly nativeType: 'geometry';
            readonly codecId: 'pg/geometry@1';
            readonly nullable: false;
            readonly typeRef: 'WgsGeometry';
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly neighborhood: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly boundary: {
            readonly nativeType: 'geometry';
            readonly codecId: 'pg/geometry@1';
            readonly nullable: false;
            readonly typeRef: 'WgsGeometry';
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly route: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly path: {
            readonly nativeType: 'geometry';
            readonly codecId: 'pg/geometry@1';
            readonly nullable: false;
            readonly typeRef: 'WgsGeometry';
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: {
      readonly WgsGeometry: {
        readonly kind: 'codec-instance';
        readonly codecId: 'pg/geometry@1';
        readonly nativeType: 'geometry';
        readonly typeParams: { readonly srid: 4326 };
      };
    };
    readonly namespaces: { readonly __unbound__: { readonly id: '__unbound__' } };
    readonly storageHash: StorageHash;
  },
  {
    readonly Cafe: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly location: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/geometry@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'cafe';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly name: { readonly column: 'name' };
          readonly location: { readonly column: 'location' };
        };
      };
    };
    readonly Neighborhood: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly boundary: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/geometry@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'neighborhood';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly name: { readonly column: 'name' };
          readonly boundary: { readonly column: 'boundary' };
        };
      };
    };
    readonly Route: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly path: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/geometry@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'route';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly name: { readonly column: 'name' };
          readonly path: { readonly column: 'path' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly cafe: 'Cafe';
    readonly route: 'Route';
    readonly neighborhood: 'Neighborhood';
  };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly 'postgis.geometry': true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {
    readonly postgis: {
      readonly capabilities: { readonly postgres: { readonly 'postgis.geometry': true } };
      readonly familyId: 'sql';
      readonly id: 'postgis';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'PostgisTypes';
            readonly named: 'CodecTypes';
            readonly package: '@prisma-next/extension-postgis/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'Geometry';
              readonly named: 'Geometry';
              readonly package: '@prisma-next/extension-postgis/codec-types';
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'PostgisQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@prisma-next/extension-postgis/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'geometry';
            readonly targetId: 'postgres';
            readonly typeId: 'pg/geometry@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'cafe'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'neighborhood'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'route'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
