// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ContractModelDefinitions,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:73f6cdc4bb9d4e8ec73d4e49360ffae395dad73b44bab7ae0c7766d24d48f9fc'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly AuthIdentity: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly user_id: CodecTypes['pg/text@1']['output'];
    readonly provider: CodecTypes['pg/text@1']['output'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['output'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly AuthUser: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly email: CodecTypes['pg/text@1']['output'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['output'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly StorageBucket: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['output'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly StorageObject: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly bucket_id: CodecTypes['pg/text@1']['output'];
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['output'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly AuthIdentity: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly user_id: CodecTypes['pg/text@1']['input'];
    readonly provider: CodecTypes['pg/text@1']['input'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['input'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly AuthUser: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly email: CodecTypes['pg/text@1']['input'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['input'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly StorageBucket: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['input'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly StorageObject: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly bucket_id: CodecTypes['pg/text@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly created_at: CodecTypes['pg/timestamptz@1']['input'];
    readonly updated_at: CodecTypes['pg/timestamptz@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly auth: {
          readonly id: 'auth';
          readonly kind: 'sql-namespace';
          readonly tables: {
            readonly identities: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly provider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
        readonly public: {
          readonly id: 'public';
          readonly kind: 'sql-namespace';
          readonly tables: {};
        };
        readonly storage: {
          readonly id: 'storage';
          readonly kind: 'sql-namespace';
          readonly tables: {
            readonly buckets: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly objects: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly bucket_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly typeRef: 'Timestamptz';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly types: {
        readonly Uuid: {
          readonly kind: 'codec-instance';
          readonly codecId: 'pg/text@1';
          readonly nativeType: 'uuid';
          readonly typeParams: Record<string, never>;
        };
        readonly Timestamptz: {
          readonly kind: 'codec-instance';
          readonly codecId: 'pg/timestamptz@1';
          readonly nativeType: 'timestamptz';
          readonly typeParams: Record<string, never>;
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly AuthIdentity: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly user_id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly provider: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly created_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
          readonly updated_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'identities';
          readonly namespaceId: 'auth';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly user_id: { readonly column: 'user_id' };
            readonly provider: { readonly column: 'provider' };
            readonly created_at: { readonly column: 'created_at' };
            readonly updated_at: { readonly column: 'updated_at' };
          };
        };
      };
      readonly AuthUser: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly email: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly created_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
          readonly updated_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'users';
          readonly namespaceId: 'auth';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly email: { readonly column: 'email' };
            readonly created_at: { readonly column: 'created_at' };
            readonly updated_at: { readonly column: 'updated_at' };
          };
        };
      };
      readonly StorageBucket: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly name: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly created_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
          readonly updated_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'buckets';
          readonly namespaceId: 'storage';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly name: { readonly column: 'name' };
            readonly created_at: { readonly column: 'created_at' };
            readonly updated_at: { readonly column: 'updated_at' };
          };
        };
      };
      readonly StorageObject: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly bucket_id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly name: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly created_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
          readonly updated_at: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'objects';
          readonly namespaceId: 'storage';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly bucket_id: { readonly column: 'bucket_id' };
            readonly name: { readonly column: 'name' };
            readonly created_at: { readonly column: 'created_at' };
            readonly updated_at: { readonly column: 'updated_at' };
          };
        };
      };
    }
  >,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'auth' & NamespaceId; readonly model: 'AuthUser' };
    readonly identities: {
      readonly namespace: 'auth' & NamespaceId;
      readonly model: 'AuthIdentity';
    };
    readonly buckets: {
      readonly namespace: 'storage' & NamespaceId;
      readonly model: 'StorageBucket';
    };
    readonly objects: {
      readonly namespace: 'storage' & NamespaceId;
      readonly model: 'StorageObject';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly auth: {
        readonly models: {
          readonly AuthIdentity: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly user_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly provider: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'identities';
              readonly namespaceId: 'auth';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly user_id: { readonly column: 'user_id' };
                readonly provider: { readonly column: 'provider' };
                readonly created_at: { readonly column: 'created_at' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly AuthUser: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'auth';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly created_at: { readonly column: 'created_at' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
      readonly storage: {
        readonly models: {
          readonly StorageBucket: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'buckets';
              readonly namespaceId: 'storage';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly created_at: { readonly column: 'created_at' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
          readonly StorageObject: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bucket_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updated_at: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'objects';
              readonly namespaceId: 'storage';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly bucket_id: { readonly column: 'bucket_id' };
                readonly name: { readonly column: 'name' };
                readonly created_at: { readonly column: 'created_at' };
                readonly updated_at: { readonly column: 'updated_at' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Models = ContractModelDefinitions<Contract>;

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
