// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { JsonValue } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';

import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type StorageHash =
  StorageHashBase<'sha256:5b624a18b8f9ac66c74cb9a5fca5115228544ccd1de6f1213f05e2e4a757a364'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:17cce12c5fab1c37ac2ec8c5907815c86bf13aaf66c80e6ce9d3834ce0912c3f'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9968c4a694e9d0bd70b959b5434f49cc8bd17deb1e4441dda4b41d13352839ab'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly id_nanoid_record: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
          };
          readonly name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly created_at: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly id_ulid_record: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
          };
          readonly note: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly created_at: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly IdNanoidRecord: {
      storage: { readonly table: 'id_nanoid_record' };
      fields: {
        readonly id: Char<21>;
        readonly name: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
    readonly IdUlidRecord: {
      storage: { readonly table: 'id_ulid_record' };
      fields: {
        readonly id: Char<26>;
        readonly note: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: {
      readonly IdNanoidRecord: 'id_nanoid_record';
      readonly IdUlidRecord: 'id_ulid_record';
    };
    tableToModel: {
      readonly id_nanoid_record: 'IdNanoidRecord';
      readonly id_ulid_record: 'IdUlidRecord';
    };
    fieldToColumn: {
      readonly IdNanoidRecord: {
        readonly id: 'id';
        readonly name: 'name';
        readonly createdAt: 'created_at';
      };
      readonly IdUlidRecord: {
        readonly id: 'id';
        readonly note: 'note';
        readonly createdAt: 'created_at';
      };
    };
    columnToField: {
      readonly id_nanoid_record: {
        readonly id: 'id';
        readonly name: 'name';
        readonly created_at: 'createdAt';
      };
      readonly id_ulid_record: {
        readonly id: 'id';
        readonly note: 'note';
        readonly created_at: 'createdAt';
      };
    };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  },
  StorageHash,
  ExecutionHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
