import { access, readFile, writeFile } from 'node:fs/promises';
import { createServer as createHttpServer } from 'node:http';
import { dirname, isAbsolute, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createServer as createViteServer } from 'vite';
import { attachBridge } from './bridge';
import { generateDefaultPostgresConfig } from './default-config';
import { findNearestConfig } from './find-config';

const PACKAGE_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const PORT = 5273;
const LSP_PATH = '/psl';

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function resolveCliEntry(): string {
  // The bridge spawns the built CLI binary (`dist/cli.js`). That path is not in
  // the package's `exports` map, so resolve the package's main export and derive
  // the sibling `cli.js` from its directory (`dist/exports/index.mjs` ->
  // `dist/cli.js`).
  const mainExport = fileURLToPath(import.meta.resolve('@prisma-next/cli'));
  return resolve(dirname(mainExport), '..', 'cli.js');
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const explicitConfigIndex = args.indexOf('--config');
  const explicitConfig = explicitConfigIndex !== -1 ? args[explicitConfigIndex + 1] : undefined;
  const positional = args.filter((a, i) => {
    if (a.startsWith('--')) return false;
    if (i > 0 && args[i - 1] === '--config') return false;
    return true;
  });
  const schemaArg = positional[0];

  if (schemaArg === undefined) {
    console.error('Usage: psl-playground <schema.psl> [--config <prisma-next.config.ts>]');
    process.exit(1);
  }

  const schemaPath = isAbsolute(schemaArg) ? schemaArg : resolve(process.cwd(), schemaArg);
  if (!(await fileExists(schemaPath))) {
    console.error(`Schema file not found: ${schemaPath}`);
    process.exit(1);
  }

  let configPath: string;
  if (explicitConfig !== undefined) {
    configPath = isAbsolute(explicitConfig)
      ? explicitConfig
      : resolve(process.cwd(), explicitConfig);
    console.log(`Using config (explicit): ${configPath}`);
  } else {
    const found = await findNearestConfig(schemaPath);
    if (found !== undefined) {
      configPath = found;
      console.log(`Using config (discovered): ${configPath}`);
    } else {
      configPath = await generateDefaultPostgresConfig(schemaPath);
      console.log(`No config found; generated default-postgres config: ${configPath}`);
    }
  }

  const cliEntry = resolveCliEntry();
  if (!(await fileExists(cliEntry))) {
    console.error(
      `Built CLI not found at ${cliEntry}.\n` +
        'Build it first:  pnpm --filter @prisma-next/cli build',
    );
    process.exit(1);
  }

  const schemaText = await readFile(schemaPath, 'utf8');
  const documentUri = pathToFileURL(schemaPath).toString();
  const rootUri = pathToFileURL(dirname(configPath)).toString();

  // Hand the browser client its runtime values via a generated module (rather
  // than Vite `define`, whose bare-identifier substitution is unreliable in the
  // programmatic dev-server path). The WS URL is relative so the editor and the
  // LSP bridge share this single origin/port.
  const runtimeModule = resolve(PACKAGE_ROOT, 'src/client/runtime.ts');
  await writeFile(
    runtimeModule,
    `// Generated by psl-playground at launch. Do not edit.
export const wsPath = ${JSON.stringify(LSP_PATH)};
export const documentUri = ${JSON.stringify(documentUri)};
export const rootUri = ${JSON.stringify(rootUri)};
export const schemaPath = ${JSON.stringify(schemaPath)};
export const schemaText = ${JSON.stringify(schemaText)};
`,
    'utf8',
  );

  // One HTTP server hosts both the editor (Vite, in middleware mode) and the
  // LSP WebSocket bridge (on LSP_PATH). Vite's HMR WebSocket is bound to the
  // same server via `hmr.server`, so a single port serves everything.
  const httpServer = createHttpServer();

  const vite = await createViteServer({
    root: PACKAGE_ROOT,
    server: {
      middlewareMode: true,
      hmr: { server: httpServer },
    },
    appType: 'spa',
  });
  httpServer.on('request', vite.middlewares);

  const stopBridge = attachBridge(httpServer, { cliEntry, configPath, path: LSP_PATH });

  httpServer.on('error', (error: NodeJS.ErrnoException) => {
    if (error.code === 'EADDRINUSE') {
      console.error(
        `Port ${PORT} is already in use — another psl-playground may be running. Stop it and retry.`,
      );
    } else {
      console.error(`Server error: ${error.message}`);
    }
    process.exit(1);
  });

  httpServer.listen(PORT, () => {
    const url = `http://localhost:${PORT}/`;
    console.log(`Playground: ${url}`);
    console.log(`LSP bridge: ws://localhost:${PORT}${LSP_PATH}`);
    console.log('Open the URL above in your browser. Ctrl+C to stop.');
  });

  const shutdown = async (): Promise<void> => {
    stopBridge();
    await vite.close();
    httpServer.close();
    process.exit(0);
  };
  process.on('SIGINT', () => void shutdown());
  process.on('SIGTERM', () => void shutdown());
}

void main();
