// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ContractModelDefinitions,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:18f562b179463260305a73e417839b92791a238722cc74565f6054929ac87ea3'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Task: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly title: CodecTypes['pg/text@1']['output'];
    readonly priority: CodecTypes['pg/text@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Task: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly title: CodecTypes['pg/text@1']['input'];
    readonly priority: CodecTypes['pg/text@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly __unbound__: {
          readonly id: '__unbound__';
          readonly kind: 'sql-namespace';
          readonly entries: { readonly table: {} };
        };
        readonly public: {
          readonly id: 'public';
          readonly kind: 'sql-namespace';
          readonly entries: {
            readonly table: {
              readonly task: {
                columns: {
                  readonly id: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                  readonly title: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                  readonly priority: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                };
                primaryKey: { readonly columns: readonly ['id'] };
                uniques: readonly [];
                indexes: readonly [];
                foreignKeys: readonly [];
              };
            };
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly Task: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly title: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly priority: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'task';
          readonly namespaceId: 'public';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly title: { readonly column: 'title' };
            readonly priority: { readonly column: 'priority' };
          };
        };
      };
    }
  >,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly task: { readonly namespace: 'public' & NamespaceId; readonly model: 'Task' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Task: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly priority: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'task';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly priority: { readonly column: 'priority' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Models = ContractModelDefinitions<Contract>;

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
