// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next emit'.
// To regenerate, run: prisma-next emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { CodecTypes as PgVectorTypes } from '@prisma-next/extension-pgvector/codec-types';
import type { OperationTypes as PgVectorOperationTypes } from '@prisma-next/extension-pgvector/operation-types';

import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type CodecTypes = PgTypes & PgVectorTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = PgVectorOperationTypes;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly user: {
        columns: {
          readonly id: { readonly type: 'pg/int4@1'; readonly nullable: false };
          readonly email: { readonly type: 'pg/text@1'; readonly nullable: false };
          readonly createdAt: { readonly type: 'pg/timestamptz@1'; readonly nullable: false };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly post: {
        columns: {
          readonly id: { readonly type: 'pg/int4@1'; readonly nullable: false };
          readonly title: { readonly type: 'pg/text@1'; readonly nullable: false };
          readonly userId: { readonly type: 'pg/int4@1'; readonly nullable: false };
          readonly createdAt: { readonly type: 'pg/timestamptz@1'; readonly nullable: false };
          readonly embedding: { readonly type: 'pg/vector@1'; readonly nullable: true };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
  },
  {
    readonly User: {
      storage: { readonly table: 'user' };
      fields: {
        readonly id: CodecTypes['pg/int4@1']['output'];
        readonly email: CodecTypes['pg/text@1']['output'];
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
    readonly Post: {
      storage: { readonly table: 'post' };
      fields: {
        readonly id: CodecTypes['pg/int4@1']['output'];
        readonly title: CodecTypes['pg/text@1']['output'];
        readonly userId: CodecTypes['pg/int4@1']['output'];
        readonly embedding: CodecTypes['pg/vector@1']['output'] | null;
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  {
    readonly user: {
      readonly posts: {
        readonly to: 'Post';
        readonly cardinality: '1:N';
        readonly on: {
          readonly parentCols: readonly ['id'];
          readonly childCols: readonly ['userId'];
        };
      };
    };
    readonly post: {
      readonly user: {
        readonly to: 'User';
        readonly cardinality: 'N:1';
        readonly on: {
          readonly parentCols: readonly ['userId'];
          readonly childCols: readonly ['id'];
        };
      };
    };
  },
  {
    modelToTable: { readonly User: 'user'; readonly Post: 'post' };
    tableToModel: { readonly user: 'User'; readonly post: 'Post' };
    fieldToColumn: {
      readonly User: {
        readonly id: 'id';
        readonly email: 'email';
        readonly createdAt: 'createdAt';
      };
      readonly Post: {
        readonly id: 'id';
        readonly title: 'title';
        readonly userId: 'userId';
        readonly embedding: 'embedding';
        readonly createdAt: 'createdAt';
      };
    };
    columnToField: {
      readonly user: {
        readonly id: 'id';
        readonly email: 'email';
        readonly createdAt: 'createdAt';
      };
      readonly post: {
        readonly id: 'id';
        readonly title: 'title';
        readonly userId: 'userId';
        readonly embedding: 'embedding';
        readonly createdAt: 'createdAt';
      };
    };
    codecTypes: PgTypes & PgVectorTypes;
    operationTypes: PgVectorOperationTypes;
  }
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
