// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { JsonValue } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';
import type { CodecTypes as PgVectorTypes } from '@prisma-next/extension-pgvector/codec-types';
import type { Vector } from '@prisma-next/extension-pgvector/codec-types';
import type { OperationTypes as PgVectorOperationTypes } from '@prisma-next/extension-pgvector/operation-types';
import type { QueryOperationTypes as PgVectorQueryOperationTypes } from '@prisma-next/extension-pgvector/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:76c1bd5f5733774ae1182e83ca882f623cdf12e78a76c2fb06666d60bbdd6452'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:516d134296237bb5f427dfe28f42f79077d0b72cbcae281fdd1ba3c974b9568e'>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes & PgVectorTypes;
export type OperationTypes = PgVectorOperationTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgVectorQueryOperationTypes;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;
export type AddressOutput = {
  readonly street: CodecTypes['pg/text@1']['output'];
  readonly city: CodecTypes['pg/text@1']['output'];
  readonly zip: CodecTypes['pg/text@1']['output'] | null;
  readonly country: CodecTypes['pg/text@1']['output'];
};
export type AddressInput = {
  readonly street: CodecTypes['pg/text@1']['input'];
  readonly city: CodecTypes['pg/text@1']['input'];
  readonly zip: CodecTypes['pg/text@1']['input'] | null;
  readonly country: CodecTypes['pg/text@1']['input'];
};
export type FieldOutputTypes = {
  readonly Bug: {
    readonly severity: CodecTypes['pg/text@1']['output'];
    readonly stepsToRepro: CodecTypes['pg/text@1']['output'] | null;
  };
  readonly Feature: {
    readonly priority: CodecTypes['pg/text@1']['output'];
    readonly targetRelease: CodecTypes['pg/text@1']['output'] | null;
  };
  readonly Post: {
    readonly id: Char<36>;
    readonly title: CodecTypes['pg/text@1']['output'];
    readonly userId: CodecTypes['pg/text@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
    readonly embedding: CodecTypes['pg/vector@1']['output'] | null;
  };
  readonly Task: {
    readonly id: Char<36>;
    readonly title: CodecTypes['pg/text@1']['output'];
    readonly description: CodecTypes['pg/text@1']['output'] | null;
    readonly status: CodecTypes['pg/text@1']['output'];
    readonly type: CodecTypes['pg/text@1']['output'];
    readonly userId: CodecTypes['pg/text@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly User: {
    readonly id: Char<36>;
    readonly email: CodecTypes['pg/text@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
    readonly kind: CodecTypes['pg/enum@1']['output'];
    readonly address: AddressOutput | null;
  };
};
export type FieldInputTypes = {
  readonly Bug: {
    readonly severity: CodecTypes['pg/text@1']['input'];
    readonly stepsToRepro: CodecTypes['pg/text@1']['input'] | null;
  };
  readonly Feature: {
    readonly priority: CodecTypes['pg/text@1']['input'];
    readonly targetRelease: CodecTypes['pg/text@1']['input'] | null;
  };
  readonly Post: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly title: CodecTypes['pg/text@1']['input'];
    readonly userId: CodecTypes['pg/text@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
    readonly embedding: CodecTypes['pg/vector@1']['input'] | null;
  };
  readonly Task: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly title: CodecTypes['pg/text@1']['input'];
    readonly description: CodecTypes['pg/text@1']['input'] | null;
    readonly status: CodecTypes['pg/text@1']['input'];
    readonly type: CodecTypes['pg/text@1']['input'];
    readonly userId: CodecTypes['pg/text@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly User: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly email: CodecTypes['pg/text@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
    readonly kind: CodecTypes['pg/enum@1']['input'];
    readonly address: AddressInput | null;
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  OperationTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly tables: {
      readonly bug: {
        columns: {
          readonly severity: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly stepsToRepro: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
        };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly feature: {
        columns: {
          readonly priority: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly targetRelease: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
        };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly post: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly title: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly userId: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly embedding: {
            readonly nativeType: 'vector';
            readonly codecId: 'pg/vector@1';
            readonly nullable: true;
            readonly typeRef: 'Embedding1536';
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['userId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly task: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly title: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly description: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly status: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
            readonly default: {
              readonly kind: 'literal';
              readonly value: DefaultLiteralValue<'pg/text@1', 'open'>;
            };
          };
          readonly type: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly userId: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [
          {
            readonly columns: readonly ['userId'];
            readonly references: { readonly table: 'user'; readonly columns: readonly ['id'] };
            readonly constraint: true;
            readonly index: true;
          },
        ];
      };
      readonly user: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly createdAt: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
          readonly kind: {
            readonly nativeType: 'user_type';
            readonly codecId: 'pg/enum@1';
            readonly nullable: false;
            readonly typeRef: 'user_type';
          };
          readonly address: {
            readonly nativeType: 'jsonb';
            readonly codecId: 'pg/jsonb@1';
            readonly nullable: true;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: {
      readonly user_type: {
        readonly codecId: 'pg/enum@1';
        readonly nativeType: 'user_type';
        readonly typeParams: { readonly values: readonly ['admin', 'user'] };
      };
      readonly Embedding1536: {
        readonly codecId: 'pg/vector@1';
        readonly nativeType: 'vector';
        readonly typeParams: { readonly length: 1536 };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Bug: {
      readonly fields: {
        readonly severity: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly stepsToRepro: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'bug';
        readonly fields: {
          readonly severity: { readonly column: 'severity' };
          readonly stepsToRepro: { readonly column: 'stepsToRepro' };
        };
      };
      readonly base: 'Task';
    };
    readonly Feature: {
      readonly fields: {
        readonly priority: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly targetRelease: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'feature';
        readonly fields: {
          readonly priority: { readonly column: 'priority' };
          readonly targetRelease: { readonly column: 'targetRelease' };
        };
      };
      readonly base: 'Task';
    };
    readonly Post: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
        readonly embedding: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/vector@1' };
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['id'];
          };
        };
      };
      readonly storage: {
        readonly table: 'post';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly title: { readonly column: 'title' };
          readonly userId: { readonly column: 'userId' };
          readonly createdAt: { readonly column: 'createdAt' };
          readonly embedding: { readonly column: 'embedding' };
        };
      };
    };
    readonly Task: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly description: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly status: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly type: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['id'];
          };
        };
      };
      readonly storage: {
        readonly table: 'task';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly title: { readonly column: 'title' };
          readonly description: { readonly column: 'description' };
          readonly status: { readonly column: 'status' };
          readonly type: { readonly column: 'type' };
          readonly userId: { readonly column: 'userId' };
          readonly createdAt: { readonly column: 'createdAt' };
        };
      };
      readonly discriminator: { readonly field: 'type' };
      readonly variants: {
        readonly Bug: { readonly value: 'bug' };
        readonly Feature: { readonly value: 'feature' };
      };
    };
    readonly User: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
        readonly kind: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/enum@1' };
        };
        readonly address: {
          readonly nullable: true;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
        };
      };
      readonly relations: {
        readonly posts: {
          readonly to: 'Post';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['userId'];
          };
        };
        readonly tasks: {
          readonly to: 'Task';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['id'];
            readonly targetFields: readonly ['userId'];
          };
        };
      };
      readonly storage: {
        readonly table: 'user';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly email: { readonly column: 'email' };
          readonly createdAt: { readonly column: 'createdAt' };
          readonly kind: { readonly column: 'kind' };
          readonly address: { readonly column: 'address' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: { readonly user: 'User'; readonly post: 'Post'; readonly task: 'Task' };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly 'pgvector.cosine': true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {
    readonly pgvector: {
      readonly capabilities: { readonly postgres: { readonly 'pgvector.cosine': true } };
      readonly familyId: 'sql';
      readonly id: 'pgvector';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'PgVectorTypes';
            readonly named: 'CodecTypes';
            readonly package: '@prisma-next/extension-pgvector/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'Vector';
              readonly named: 'Vector';
              readonly package: '@prisma-next/extension-pgvector/codec-types';
            },
          ];
        };
        readonly operationTypes: {
          readonly import: {
            readonly alias: 'PgVectorOperationTypes';
            readonly named: 'OperationTypes';
            readonly package: '@prisma-next/extension-pgvector/operation-types';
          };
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'PgVectorQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@prisma-next/extension-pgvector/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'vector';
            readonly targetId: 'postgres';
            readonly typeId: 'pg/vector@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'post'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'task'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'user'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};
  readonly valueObjects: {
    readonly Address: {
      readonly fields: {
        readonly street: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly zip: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
