import { QueryBuilder } from './builder';
import { compileToSQL } from './compiler';

export function sql() {
  return {
    from(tableName: string): QueryBuilder {
      return new QueryBuilder(tableName);
    },
  };
}

// This would be imported from generated schema.d.ts
export const t = {
  // Placeholder - this will be generated by schema-emitter
  user: {
    id: {
      eq: (value: number) => ({ type: 'eq' as const, field: 'id', value }),
      ne: (value: number) => ({ type: 'ne' as const, field: 'id', value }),
      gt: (value: number) => ({ type: 'gt' as const, field: 'id', value }),
      lt: (value: number) => ({ type: 'lt' as const, field: 'id', value }),
      gte: (value: number) => ({ type: 'gte' as const, field: 'id', value }),
      lte: (value: number) => ({ type: 'lte' as const, field: 'id', value }),
      in: (values: number[]) => ({ type: 'in' as const, field: 'id', values }),
    },
    email: {
      eq: (value: string) => ({ type: 'eq' as const, field: 'email', value }),
      ne: (value: string) => ({ type: 'ne' as const, field: 'email', value }),
      gt: (value: string) => ({ type: 'gt' as const, field: 'email', value }),
      lt: (value: string) => ({ type: 'lt' as const, field: 'email', value }),
      gte: (value: string) => ({ type: 'gte' as const, field: 'email', value }),
      lte: (value: string) => ({ type: 'lte' as const, field: 'email', value }),
      in: (values: string[]) => ({ type: 'in' as const, field: 'email', values }),
    },
    active: {
      eq: (value: boolean) => ({ type: 'eq' as const, field: 'active', value }),
      ne: (value: boolean) => ({ type: 'ne' as const, field: 'active', value }),
      gt: (value: boolean) => ({ type: 'gt' as const, field: 'active', value }),
      lt: (value: boolean) => ({ type: 'lt' as const, field: 'active', value }),
      gte: (value: boolean) => ({ type: 'gte' as const, field: 'active', value }),
      lte: (value: boolean) => ({ type: 'lte' as const, field: 'active', value }),
      in: (values: boolean[]) => ({ type: 'in' as const, field: 'active', values }),
    },
    createdAt: {
      eq: (value: Date) => ({ type: 'eq' as const, field: 'createdAt', value }),
      ne: (value: Date) => ({ type: 'ne' as const, field: 'createdAt', value }),
      gt: (value: Date) => ({ type: 'gt' as const, field: 'createdAt', value }),
      lt: (value: Date) => ({ type: 'lt' as const, field: 'createdAt', value }),
      gte: (value: Date) => ({ type: 'gte' as const, field: 'createdAt', value }),
      lte: (value: Date) => ({ type: 'lte' as const, field: 'createdAt', value }),
      in: (values: Date[]) => ({ type: 'in' as const, field: 'createdAt', values }),
    },
  },
};

export { compileToSQL };
export * from './types';
