// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:b41a153d3d076ecfdf4e4e232153af17a773fc3fd418f2c7f5b5228f54e29bf6'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly User: {
    readonly id: CodecTypes['pg/int4@1']['output'];
    readonly email: CodecTypes['pg/text@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly User: {
    readonly id: CodecTypes['pg/int4@1']['input'];
    readonly email: CodecTypes['pg/text@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly storageHash: StorageHash;
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sql-namespace';
        readonly tables: {
          readonly user: {
            columns: {
              readonly id: {
                readonly nativeType: 'int4';
                readonly codecId: 'pg/int4@1';
                readonly nullable: false;
              };
              readonly email: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly createdAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ['id'] };
            uniques: readonly [];
            indexes: readonly [];
            foreignKeys: readonly [];
          };
        };
      };
    },
    {
      readonly User: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
          };
          readonly email: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly createdAt: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'user';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly email: { readonly column: 'email' };
            readonly createdAt: { readonly column: 'createdAt' };
          };
        };
      };
    }
  >,
  'roots'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly user: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Omit<Contract['storage'], 'storageHash' | 'types'>;
export type Models = Contract['models'];
