/**
 * Infer -> Emit Round-Trip Fidelity (TML-3037, dispatch D1 — the instrument)
 *
 * `contract-infer-workflow.e2e.test.ts` already proves infer -> emit -> verify
 * on a two-column table. This journey runs the same shape against a schema
 * that carries the fidelity gaps TML-3037 tracks: an already-plural
 * back-relation target, a 1:1 FK, a 1:N FK, both `GENERATED ... AS IDENTITY`
 * variants plus a `serial` control column, a GIN index, a `USING hash` index,
 * array/jsonb defaults, and a foreign key into a schema outside the
 * introspected scope.
 *
 * Each `it()` isolates one defect so a single run reports every defect
 * independently instead of stopping at the first failure. Where an
 * unfixed defect would otherwise block `contract emit` before a later
 * defect gets a chance to run, the PSL is surgically reduced (fixing
 * everything except the one thing under test) so that defect's own error
 * surfaces on its own.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { withClient } from '@prisma-next/test-utils';
import stripAnsi from 'strip-ansi';
import { describe, expect, it } from 'vitest';
import { withTempDir } from '../utils/cli-test-helpers';
import {
  type JourneyContext,
  runContractEmit,
  runContractInfer,
  runDbVerify,
  setupJourney,
  timeouts,
  useDevDatabase,
} from '../utils/journey-test-helpers';

const SEED_SQL = `
  CREATE SCHEMA secure;
  CREATE TABLE secure.owners (
    id int4 PRIMARY KEY
  );

  CREATE TABLE users (
    id int4 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    balance numeric,
    precise_balance numeric(10,2),
    birth_date date,
    tags text[] NOT NULL DEFAULT '{}'::text[],
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
  );
  CREATE INDEX users_metadata_gin_idx ON users USING gin (metadata);

  CREATE TABLE sessions (
    id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int4 NOT NULL REFERENCES users(id),
    owner_ref int4 REFERENCES secure.owners(id)
  );

  CREATE TABLE identities (
    id serial PRIMARY KEY,
    user_id int4 NOT NULL UNIQUE REFERENCES users(id),
    provider text NOT NULL
  );
  CREATE INDEX identities_provider_hash_idx ON identities USING hash (provider);
`;

function readContractPsl(ctx: JourneyContext): string {
  return readFileSync(join(ctx.testDir, 'contract.prisma'), 'utf-8');
}

function writeContractPsl(ctx: JourneyContext, psl: string): void {
  writeFileSync(join(ctx.testDir, 'contract.prisma'), psl, 'utf-8');
}

/** Removes the bare, `@relation`-less 1:1 back-relation field infer prints on `Users`. */
function fixOneToOneBackRelation(psl: string): string {
  return psl.replace(/^\s*identities\s+Identities\?\s*$\n/m, '');
}

/** Removes the storage-level list default infer prints on `Users.tags`. */
function fixListDefault(psl: string): string {
  return psl.replace(/\s*@default\(dbgenerated\("'\{\}'::text\[\]"\)\)/, '');
}

/** Strips the non-btree `type:` argument infer prints on both `@@index` attributes. */
function fixIndexTypes(psl: string): string {
  return psl.replace(/,\s*type: "(?:gin|hash)"/g, '');
}

/**
 * Drops the two non-btree `@@index` attributes entirely, rather than just
 * their `type:` argument. Stripping only the argument leaves a contract that
 * declares those indexes as plain btree, which live verify then reports as a
 * type mismatch against the real gin/hash indexes — an artifact of the
 * reduction, not one of the eight defects. Dropping the attribute instead
 * makes the index an undeclared "extra", which non-strict schema-only verify
 * tolerates, isolating whatever defect a test is actually probing.
 */
function dropNonBtreeIndexes(psl: string): string {
  return psl.replace(/^\s*@@index\(\[\w+\], map: "[^"]+", type: "(?:gin|hash)"\)\s*$\n/gm, '');
}

withTempDir(({ createTempDir }) => {
  describe('Journey: Infer -> Emit Round-Trip Fidelity', () => {
    const db = useDevDatabase({
      onReady: (cs) => withClient(cs, (client) => client.query(SEED_SQL)),
    });

    it(
      'IF.01: back-relation naming — an already-plural child table does not double-pluralize',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.01: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        expect(
          psl,
          'IF.01: Users back-relation to the plural "sessions" table is "sessions", not "sessionses"',
        ).toMatch(/\bsessions\s+Sessions\[\]/);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.02: the interpreter accepts the 1:1 back-relation infer prints for a unique FK',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.02: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Isolate the 1:1 back-relation defect: fix the two unrelated
        // emit-blockers (list default, non-btree index types) so any failure
        // here is attributable to the 1:1 back-relation alone.
        const reduced = fixIndexTypes(fixListDefault(readContractPsl(ctx)));
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `IF.02: contract emit should accept the bare "identities Identities?" 1:1 back-relation ` +
            `field; instead got:\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.03: the interpreter accepts the storage-level list default infer prints for text[]',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.03: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Isolate the list-default defect: fix the two unrelated emit-blockers
        // (1:1 back-relation, non-btree index types).
        const reduced = fixIndexTypes(fixOneToOneBackRelation(readContractPsl(ctx)));
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `IF.03: contract emit should accept @default(dbgenerated("'{}'::text[]")) on Users.tags; ` +
            `instead got:\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.04: postgres registers the gin and hash index types infer already prints',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.04: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Isolate the index-type defect: fix the two unrelated emit-blockers
        // (1:1 back-relation, list default).
        const reduced = fixListDefault(fixOneToOneBackRelation(readContractPsl(ctx)));
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `IF.04: contract emit should accept @@index(..., type: "gin"/"hash"); instead got:\n` +
            `${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.05: a foreign key outside the introspected schema surfaces an explanatory comment',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.05: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        // sessions.owner_ref points at secure.owners, outside the introspected
        // `public` schema — the scalar column must survive...
        expect(psl, 'IF.05: dangling FK keeps its scalar column').toContain('ownerRef');
        // ...and the model must explain why the relation is missing, the same
        // way infer already documents a table with no primary key.
        expect(
          psl,
          'IF.05: Sessions documents the dropped cross-schema relation with a comment',
        ).toMatch(/\/\/[^\n]*\nmodel Sessions \{/);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.06: identity columns (both GENERATED variants) round-trip as autoincrement(); serial keeps working',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.06: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const psl = readContractPsl(ctx);
        expect(psl, 'IF.06: serial column already carries autoincrement() (control)').toMatch(
          /id\s+Int\s+@id\(map: "identities_pkey"\)\s+@default\(autoincrement\(\)\)/,
        );
        expect(
          psl,
          'IF.06: GENERATED ALWAYS AS IDENTITY (users.id) carries autoincrement()',
        ).toMatch(/id\s+Int\s+@id\(map: "users_pkey"\)\s+@default\(autoincrement\(\)\)/);
        expect(
          psl,
          'IF.06: GENERATED BY DEFAULT AS IDENTITY (sessions.id) carries autoincrement()',
        ).toMatch(/id\s+Int\s+@id\(map: "sessions_pkey"\)\s+@default\(autoincrement\(\)\)/);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.07: a jsonb literal default round-trips clean through db verify --schema-only',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.07: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        // Fix the three unrelated emit-blockers so emit succeeds and verify
        // can run; the jsonb default on Users.metadata is left untouched.
        // The two non-btree indexes are dropped (not just detyped) so they
        // become undeclared "extras" that non-strict verify tolerates,
        // rather than a declared-btree-vs-live-gin/hash type mismatch that
        // would otherwise mask the jsonb-default assertion this test is for.
        const reduced = dropNonBtreeIndexes(
          fixListDefault(fixOneToOneBackRelation(readContractPsl(ctx))),
        );
        writeContractPsl(ctx, reduced);

        const emit = await runContractEmit(ctx);
        expect(emit.exitCode, `IF.07: contract emit\n${stripAnsi(emit.stderr)}`).toBe(0);

        const verify = await runDbVerify(ctx, ['--schema-only']);
        expect(
          verify.exitCode,
          `IF.07: db verify --schema-only should be clean for Users.metadata; instead got:\n${stripAnsi(verify.stderr)}\n${stripAnsi(verify.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );

    it(
      'IF.08: full round trip — infer -> emit -> db verify --schema-only, no hand-editing',
      async () => {
        const ctx: JourneyContext = setupJourney({
          connectionString: db.connectionString,
          createTempDir,
          contractMode: 'psl',
        });

        const infer = await runContractInfer(ctx);
        expect(infer.exitCode, `IF.08: contract infer\n${stripAnsi(infer.stderr)}`).toBe(0);

        const emit = await runContractEmit(ctx);
        expect(
          emit.exitCode,
          `IF.08: contract emit (unmodified inferred PSL)\n${stripAnsi(emit.stderr)}\n${stripAnsi(emit.stdout)}`,
        ).toBe(0);

        const verify = await runDbVerify(ctx, ['--schema-only']);
        expect(
          verify.exitCode,
          `IF.08: db verify --schema-only\n${stripAnsi(verify.stderr)}\n${stripAnsi(verify.stdout)}`,
        ).toBe(0);
      },
      timeouts.spinUpPpgDev,
    );
  });
});
