// Auto-generated mirror of the @prisma-next/extension-supabase contract.
// Regenerated by `prisma-next install` (or equivalent). Do not edit by hand.
//
// DESIGN HOLE #17: TypedContract<T>'s exact shape. The handle returned by
// `supabase.contract<Contract>(json)` exposes `.models.<Name>.refs.<field>`
// accessors used by FK references. The type-level mapping from this Contract
// type to those accessors lives in @prisma-next/contract-core and is part of
// the implementation work.

import type { TypedContract } from '@prisma-next/contract-core';

export interface Contract
  extends TypedContract<{
    spaceId: 'supabase';
    namespaces: ['auth', 'storage'];
    defaultPosture: 'externally-managed';
    models: {
      AuthUser: {
        namespace: 'auth';
        tableName: 'users';
        fields: {
          id: { type: 'uuid'; primary: true };
          email: { type: 'text'; nullable: true };
          phone: { type: 'text'; nullable: true };
          emailConfirmedAt: { type: 'timestamptz'; nullable: true };
          createdAt: { type: 'timestamptz' };
          updatedAt: { type: 'timestamptz' };
        };
      };
      StorageBucket: {
        namespace: 'storage';
        tableName: 'buckets';
        fields: {
          id: { type: 'text'; primary: true };
          name: { type: 'text' };
          public: { type: 'boolean' };
          createdAt: { type: 'timestamptz' };
          updatedAt: { type: 'timestamptz' };
        };
      };
    };
    // DESIGN HOLE #15-16: functions IR shape. Modeled here as a sibling to
    // `models` with `{ namespace, name }` separation matching the model
    // convention. `posture: 'externally-managed'` is inherited from the
    // contract-level defaultPosture.
    functions: {
      uid: { namespace: 'auth'; returns: { type: 'uuid' }; args: [] };
      jwt: { namespace: 'auth'; returns: { type: 'jsonb' }; args: [] };
      role: { namespace: 'auth'; returns: { type: 'text' }; args: [] };
    };
  }> {}
