// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ContractModelsMap,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:9a894cd9ffe5e3f81cab11b4bfa450c37efbf07cc84b6f53f3e5999e5f683ef8'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly EqlV2Configuration: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly state: CodecTypes['pg/text@1']['output'];
    readonly data: CodecTypes['pg/jsonb@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly EqlV2Configuration: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly state: CodecTypes['pg/text@1']['input'];
    readonly data: CodecTypes['pg/jsonb@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly __unbound__: {
          readonly id: '__unbound__';
          readonly kind: 'sql-namespace';
          readonly tables: {
            readonly eql_v2_configuration: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly data: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly EqlV2Configuration: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly state: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly data: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'eql_v2_configuration';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly state: { readonly column: 'state' };
            readonly data: { readonly column: 'data' };
          };
        };
      };
    }
  >,
  'roots'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly eql_v2_configuration: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'EqlV2Configuration';
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = ContractModelsMap<Contract>;
