// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/target-postgres/codec-types';
import type { JsonValue } from '@prisma-next/target-postgres/codec-types';
import type { Char } from '@prisma-next/target-postgres/codec-types';
import type { Varchar } from '@prisma-next/target-postgres/codec-types';
import type { Numeric } from '@prisma-next/target-postgres/codec-types';
import type { Bit } from '@prisma-next/target-postgres/codec-types';
import type { VarBit } from '@prisma-next/target-postgres/codec-types';
import type { Timestamp } from '@prisma-next/target-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/target-postgres/codec-types';
import type { Time } from '@prisma-next/target-postgres/codec-types';
import type { Timetz } from '@prisma-next/target-postgres/codec-types';
import type { Interval } from '@prisma-next/target-postgres/codec-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:5fde95fc595b8f1a040f5e6dd986cd913d07c018319d6fa18fdbeb6d507489ec'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;

export type FieldOutputTypes = {
  readonly EqlV2Configuration: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly state: CodecTypes['pg/text@1']['output'];
    readonly data: CodecTypes['pg/jsonb@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly EqlV2Configuration: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly state: CodecTypes['pg/text@1']['input'];
    readonly data: CodecTypes['pg/jsonb@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sql-namespace';
        readonly tables: {
          readonly eql_v2_configuration: {
            columns: {
              readonly id: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly state: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly data: {
                readonly nativeType: 'jsonb';
                readonly codecId: 'pg/jsonb@1';
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ['id'] };
            uniques: readonly [];
            indexes: readonly [];
            foreignKeys: readonly [];
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly EqlV2Configuration: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly state: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly data: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'eql_v2_configuration';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly state: { readonly column: 'state' };
          readonly data: { readonly column: 'data' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: { readonly eql_v2_configuration: 'EqlV2Configuration' };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = Contract['models'];
