// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ContractModelDefinitions,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:59aa59ab2038a667008a6940a27b727e6ba755085d104b25e32b075e3c484e36'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:09bd7caf0ad111e77df2565dce0c4c5b0b784f9d3dfe5c97f969f1016a6b66bb'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Profile: {
    readonly id: Char<36>;
    readonly username: CodecTypes['pg/text@1']['output'];
    readonly owner_id: CodecTypes['pg/text@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Profile: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly username: CodecTypes['pg/text@1']['input'];
    readonly owner_id: CodecTypes['pg/text@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly __unbound__: {
          readonly id: '__unbound__';
          readonly kind: 'postgres-unbound-schema';
          readonly entries: { readonly table: {}; readonly type: Record<string, never> };
        };
        readonly public: {
          readonly id: 'public';
          readonly kind: 'postgres-schema';
          readonly entries: {
            readonly table: {
              readonly profile: {
                columns: {
                  readonly id: {
                    readonly nativeType: 'character';
                    readonly codecId: 'sql/char@1';
                    readonly nullable: false;
                    readonly typeParams: { readonly length: 36 };
                  };
                  readonly username: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                  readonly owner_id: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                };
                primaryKey: { readonly columns: readonly ['id'] };
                uniques: readonly [];
                indexes: readonly [];
                foreignKeys: readonly [];
              };
            };
            readonly type: Record<string, never>;
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly Profile: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'sql/char@1';
              readonly typeParams: { readonly length: 36 };
            };
          };
          readonly username: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly owner_id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'profile';
          readonly namespaceId: 'public';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly username: { readonly column: 'username' };
            readonly owner_id: { readonly column: 'owner_id' };
          };
        };
      };
    }
  >,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly profile: { readonly namespace: 'public' & NamespaceId; readonly model: 'Profile' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Profile: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly username: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly owner_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'profile';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly username: { readonly column: 'username' };
                readonly owner_id: { readonly column: 'owner_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {
    readonly supabase: {
      readonly familyId: 'sql';
      readonly id: 'supabase';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly version: '0.12.0';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'profile'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Models = ContractModelDefinitions<Contract>;

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
