// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as SqliteTypes } from '@prisma-next/adapter-sqlite/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:e8b070318ddd3ad2730e1724f4716fb06145c5288e6edaad0be3f551bde1ab09'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:3cc333ecad9f3f4c7229370a9d2c37e908cdce0f8d2e9fb132d50605b024eff2'>;

export type CodecTypes = SqliteTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly _PostToTag: {
      readonly A: CodecTypes['sqlite/integer@1']['output'];
      readonly B: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Post: {
      readonly id: CodecTypes['sqlite/integer@1']['output'];
      readonly title: CodecTypes['sqlite/text@1']['output'];
    };
    readonly Tag: {
      readonly id: CodecTypes['sqlite/text@1']['output'];
      readonly label: CodecTypes['sqlite/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly _PostToTag: {
      readonly A: CodecTypes['sqlite/integer@1']['input'];
      readonly B: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Post: {
      readonly id: CodecTypes['sqlite/integer@1']['input'];
      readonly title: CodecTypes['sqlite/text@1']['input'];
    };
    readonly Tag: {
      readonly id: CodecTypes['sqlite/text@1']['input'];
      readonly label: CodecTypes['sqlite/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sqlite-namespace';
        readonly entries: {
          readonly table: {
            readonly _PostToTag: {
              columns: {
                readonly A: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly B: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['A', 'B'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: '_PostToTag';
                    readonly columns: readonly ['A'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'posts';
                    readonly columns: readonly ['id'];
                  };
                  readonly constraint: true;
                  readonly index: true;
                },
                {
                  readonly source: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: '_PostToTag';
                    readonly columns: readonly ['B'];
                  };
                  readonly target: {
                    readonly namespaceId: '__unbound__' & NamespaceId;
                    readonly tableName: 'tags';
                    readonly columns: readonly ['id'];
                  };
                  readonly constraint: true;
                  readonly index: true;
                },
              ];
            };
            readonly posts: {
              columns: {
                readonly id: {
                  readonly nativeType: 'integer';
                  readonly codecId: 'sqlite/integer@1';
                  readonly nullable: false;
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly tags: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'text';
                  readonly codecId: 'sqlite/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['label'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'sqlite';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly posts: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Post' };
    readonly tags: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Tag' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly _PostToTag: {
            readonly fields: {
              readonly A: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly B: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: '_PostToTag';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly A: { readonly column: 'A' };
                readonly B: { readonly column: 'B' };
              };
            };
          };
          readonly Post: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/integer@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly tags: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Tag';
                };
                readonly cardinality: 'N:M';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['A'];
                };
                readonly through: {
                  readonly table: '_PostToTag';
                  readonly namespaceId: '__unbound__';
                  readonly parentColumns: readonly ['A'];
                  readonly childColumns: readonly ['B'];
                  readonly targetColumns: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'posts';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
              };
            };
          };
          readonly Tag: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'sqlite/text@1' };
              };
            };
            readonly relations: {
              readonly posts: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Post';
                };
                readonly cardinality: 'N:M';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['B'];
                };
                readonly through: {
                  readonly table: '_PostToTag';
                  readonly namespaceId: '__unbound__';
                  readonly parentColumns: readonly ['B'];
                  readonly childColumns: readonly ['A'];
                  readonly targetColumns: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'tags';
              readonly namespaceId: '__unbound__';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly label: { readonly column: 'label' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly sql: {
      readonly enums: false;
      readonly foreignKeys: true;
      readonly jsonAgg: true;
      readonly lateral: false;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
