export type {
  // Control* types (ADR 151)
  ControlAdapterDescriptor,
  ControlAdapterInstance,
  ControlDriverDescriptor,
  ControlDriverInstance,
  ControlExtensionDescriptor,
  ControlExtensionInstance,
  ControlFamilyDescriptor,
  ControlFamilyInstance,
  ControlTargetDescriptor,
  ControlTargetInstance,
  EmitContractResult,
  IntrospectSchemaResult,
  // Migration types (canonical, family-agnostic)
  MigrationOperationClass,
  MigrationOperationPolicy,
  MigrationPlan,
  MigrationPlanner,
  MigrationPlannerConflict,
  MigrationPlannerFailureResult,
  MigrationPlannerResult,
  MigrationPlannerSuccessResult,
  MigrationPlanOperation,
  MigrationRunner,
  MigrationRunnerFailure,
  MigrationRunnerResult,
  MigrationRunnerSuccessValue,
  OperationContext,
  SchemaIssue,
  SchemaVerificationNode,
  SignDatabaseResult,
  TargetMigrationsCapability,
  VerifyDatabaseResult,
  VerifyDatabaseSchemaResult,
} from '../types';
