export type {
  // Control* types (re-exported from @prisma-next/framework-components/control)
  ControlAdapterDescriptor,
  ControlAdapterInstance,
  ControlDriverDescriptor,
  ControlDriverInstance,
  ControlExtensionDescriptor,
  ControlExtensionInstance,
  ControlFamilyDescriptor,
  ControlFamilyInstance,
  ControlPlaneStack,
  ControlStack,
  ControlTargetDescriptor,
  ControlTargetInstance,
  EmitContractResult,
  IntrospectSchemaResult,
  // Capability interfaces
  MigratableTargetDescriptor,
  // Migration types (canonical, family-agnostic)
  MigrationOperationClass,
  MigrationOperationPolicy,
  MigrationPlan,
  MigrationPlanner,
  MigrationPlannerConflict,
  MigrationPlannerFailureResult,
  MigrationPlannerResult,
  MigrationPlannerSuccessResult,
  MigrationPlanOperation,
  MigrationRunner,
  MigrationRunnerExecutionChecks,
  MigrationRunnerFailure,
  MigrationRunnerResult,
  MigrationRunnerSuccessValue,
  OperationContext,
  SchemaIssue,
  SchemaVerificationNode,
  SchemaViewCapable,
  SignDatabaseResult,
  TargetMigrationsCapability,
  VerifyDatabaseResult,
  VerifyDatabaseSchemaResult,
} from '../types';

export { hasMigrations, hasSchemaView } from '../types';
