// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as MongoCodecTypes } from '@prisma-next/adapter-mongo/codec-types';
import type { Vector } from '@prisma-next/adapter-mongo/codec-types';

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:5f5aee268e41d345787b7c5d396778443a977b10dc2ec9f14c913171fd6d1411'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:840de65fba7eb950a31487f74ee420b9c21205f38bce58579026747e0264e840'>;

export type CodecTypes = MongoCodecTypes;
export type OperationTypes = Record<string, never>;

export type PriceOutput = {
  readonly amount: CodecTypes['mongo/double@1']['output'];
  readonly currency: CodecTypes['mongo/string@1']['output'];
};
export type PriceInput = {
  readonly amount: CodecTypes['mongo/double@1']['input'];
  readonly currency: CodecTypes['mongo/string@1']['input'];
};
export type ImageOutput = { readonly url: CodecTypes['mongo/string@1']['output'] };
export type ImageInput = { readonly url: CodecTypes['mongo/string@1']['input'] };
export type AddressOutput = {
  readonly streetAndNumber: CodecTypes['mongo/string@1']['output'];
  readonly city: CodecTypes['mongo/string@1']['output'];
  readonly postalCode: CodecTypes['mongo/string@1']['output'];
  readonly country: CodecTypes['mongo/string@1']['output'];
};
export type AddressInput = {
  readonly streetAndNumber: CodecTypes['mongo/string@1']['input'];
  readonly city: CodecTypes['mongo/string@1']['input'];
  readonly postalCode: CodecTypes['mongo/string@1']['input'];
  readonly country: CodecTypes['mongo/string@1']['input'];
};
export type CartItemOutput = {
  readonly productId: CodecTypes['mongo/string@1']['output'];
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly brand: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly price: PriceOutput;
  readonly image: ImageOutput;
};
export type CartItemInput = {
  readonly productId: CodecTypes['mongo/string@1']['input'];
  readonly name: CodecTypes['mongo/string@1']['input'];
  readonly brand: CodecTypes['mongo/string@1']['input'];
  readonly amount: CodecTypes['mongo/int32@1']['input'];
  readonly price: PriceInput;
  readonly image: ImageInput;
};
export type OrderLineItemOutput = {
  readonly productId: CodecTypes['mongo/string@1']['output'];
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly brand: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly price: PriceOutput;
  readonly image: ImageOutput;
};
export type OrderLineItemInput = {
  readonly productId: CodecTypes['mongo/string@1']['input'];
  readonly name: CodecTypes['mongo/string@1']['input'];
  readonly brand: CodecTypes['mongo/string@1']['input'];
  readonly amount: CodecTypes['mongo/int32@1']['input'];
  readonly price: PriceInput;
  readonly image: ImageInput;
};
export type StatusEntryOutput = {
  readonly status: CodecTypes['mongo/string@1']['output'];
  readonly timestamp: CodecTypes['mongo/date@1']['output'];
};
export type StatusEntryInput = {
  readonly status: CodecTypes['mongo/string@1']['input'];
  readonly timestamp: CodecTypes['mongo/date@1']['input'];
};
export type InvoiceLineItemOutput = {
  readonly name: CodecTypes['mongo/string@1']['output'];
  readonly amount: CodecTypes['mongo/int32@1']['output'];
  readonly unitPrice: CodecTypes['mongo/double@1']['output'];
  readonly lineTotal: CodecTypes['mongo/double@1']['output'];
};
export type InvoiceLineItemInput = {
  readonly name: CodecTypes['mongo/string@1']['input'];
  readonly amount: CodecTypes['mongo/int32@1']['input'];
  readonly unitPrice: CodecTypes['mongo/double@1']['input'];
  readonly lineTotal: CodecTypes['mongo/double@1']['input'];
};
export type FieldOutputTypes = {
  readonly AddToCartEvent: {
    readonly productId: CodecTypes['mongo/string@1']['output'];
    readonly brand: CodecTypes['mongo/string@1']['output'];
  };
  readonly Cart: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly userId: CodecTypes['mongo/objectId@1']['output'];
    readonly items: ReadonlyArray<CartItemOutput>;
  };
  readonly Event: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly userId: CodecTypes['mongo/string@1']['output'];
    readonly sessionId: CodecTypes['mongo/string@1']['output'];
    readonly type: CodecTypes['mongo/string@1']['output'];
    readonly timestamp: CodecTypes['mongo/date@1']['output'];
  };
  readonly Invoice: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly orderId: CodecTypes['mongo/objectId@1']['output'];
    readonly items: ReadonlyArray<InvoiceLineItemOutput>;
    readonly subtotal: CodecTypes['mongo/double@1']['output'];
    readonly tax: CodecTypes['mongo/double@1']['output'];
    readonly total: CodecTypes['mongo/double@1']['output'];
    readonly issuedAt: CodecTypes['mongo/date@1']['output'];
  };
  readonly Location: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly streetAndNumber: CodecTypes['mongo/string@1']['output'];
    readonly city: CodecTypes['mongo/string@1']['output'];
    readonly postalCode: CodecTypes['mongo/string@1']['output'];
    readonly country: CodecTypes['mongo/string@1']['output'];
  };
  readonly Order: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly userId: CodecTypes['mongo/objectId@1']['output'];
    readonly items: ReadonlyArray<OrderLineItemOutput>;
    readonly shippingAddress: CodecTypes['mongo/string@1']['output'];
    readonly type: CodecTypes['mongo/string@1']['output'];
    readonly statusHistory: ReadonlyArray<StatusEntryOutput>;
  };
  readonly Product: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly brand: CodecTypes['mongo/string@1']['output'];
    readonly code: CodecTypes['mongo/string@1']['output'];
    readonly description: CodecTypes['mongo/string@1']['output'];
    readonly masterCategory: CodecTypes['mongo/string@1']['output'];
    readonly subCategory: CodecTypes['mongo/string@1']['output'];
    readonly articleType: CodecTypes['mongo/string@1']['output'];
    readonly price: PriceOutput;
    readonly image: ImageOutput;
    readonly embedding: ReadonlyArray<CodecTypes['mongo/double@1']['output']> | null;
  };
  readonly SearchEvent: { readonly query: CodecTypes['mongo/string@1']['output'] };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['output'];
    readonly name: CodecTypes['mongo/string@1']['output'];
    readonly email: CodecTypes['mongo/string@1']['output'];
    readonly address: AddressOutput | null;
  };
  readonly ViewProductEvent: {
    readonly productId: CodecTypes['mongo/string@1']['output'];
    readonly subCategory: CodecTypes['mongo/string@1']['output'];
    readonly brand: CodecTypes['mongo/string@1']['output'];
    readonly exitMethod: CodecTypes['mongo/string@1']['output'] | null;
  };
};
export type FieldInputTypes = {
  readonly AddToCartEvent: {
    readonly productId: CodecTypes['mongo/string@1']['input'];
    readonly brand: CodecTypes['mongo/string@1']['input'];
  };
  readonly Cart: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly userId: CodecTypes['mongo/objectId@1']['input'];
    readonly items: ReadonlyArray<CartItemInput>;
  };
  readonly Event: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly userId: CodecTypes['mongo/string@1']['input'];
    readonly sessionId: CodecTypes['mongo/string@1']['input'];
    readonly type: CodecTypes['mongo/string@1']['input'];
    readonly timestamp: CodecTypes['mongo/date@1']['input'];
  };
  readonly Invoice: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly orderId: CodecTypes['mongo/objectId@1']['input'];
    readonly items: ReadonlyArray<InvoiceLineItemInput>;
    readonly subtotal: CodecTypes['mongo/double@1']['input'];
    readonly tax: CodecTypes['mongo/double@1']['input'];
    readonly total: CodecTypes['mongo/double@1']['input'];
    readonly issuedAt: CodecTypes['mongo/date@1']['input'];
  };
  readonly Location: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly name: CodecTypes['mongo/string@1']['input'];
    readonly streetAndNumber: CodecTypes['mongo/string@1']['input'];
    readonly city: CodecTypes['mongo/string@1']['input'];
    readonly postalCode: CodecTypes['mongo/string@1']['input'];
    readonly country: CodecTypes['mongo/string@1']['input'];
  };
  readonly Order: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly userId: CodecTypes['mongo/objectId@1']['input'];
    readonly items: ReadonlyArray<OrderLineItemInput>;
    readonly shippingAddress: CodecTypes['mongo/string@1']['input'];
    readonly type: CodecTypes['mongo/string@1']['input'];
    readonly statusHistory: ReadonlyArray<StatusEntryInput>;
  };
  readonly Product: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly name: CodecTypes['mongo/string@1']['input'];
    readonly brand: CodecTypes['mongo/string@1']['input'];
    readonly code: CodecTypes['mongo/string@1']['input'];
    readonly description: CodecTypes['mongo/string@1']['input'];
    readonly masterCategory: CodecTypes['mongo/string@1']['input'];
    readonly subCategory: CodecTypes['mongo/string@1']['input'];
    readonly articleType: CodecTypes['mongo/string@1']['input'];
    readonly price: PriceInput;
    readonly image: ImageInput;
    readonly embedding: ReadonlyArray<CodecTypes['mongo/double@1']['input']> | null;
  };
  readonly SearchEvent: { readonly query: CodecTypes['mongo/string@1']['input'] };
  readonly User: {
    readonly _id: CodecTypes['mongo/objectId@1']['input'];
    readonly name: CodecTypes['mongo/string@1']['input'];
    readonly email: CodecTypes['mongo/string@1']['input'];
    readonly address: AddressInput | null;
  };
  readonly ViewProductEvent: {
    readonly productId: CodecTypes['mongo/string@1']['input'];
    readonly subCategory: CodecTypes['mongo/string@1']['input'];
    readonly brand: CodecTypes['mongo/string@1']['input'];
    readonly exitMethod: CodecTypes['mongo/string@1']['input'] | null;
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = ContractType<
  {
    readonly collections: {
      readonly products: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [
              { readonly field: 'name'; readonly direction: 'text' },
              { readonly field: 'description'; readonly direction: 'text' },
            ];
            readonly weights: { readonly name: 10; readonly description: 1 };
          },
          {
            readonly keys: readonly [
              { readonly field: 'brand'; readonly direction: 1 },
              { readonly field: 'subCategory'; readonly direction: 1 },
            ];
          },
          { readonly keys: readonly [{ readonly field: 'code'; readonly direction: 'hashed' }] },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly name: { readonly bsonType: 'string' };
              readonly brand: { readonly bsonType: 'string' };
              readonly code: { readonly bsonType: 'string' };
              readonly description: { readonly bsonType: 'string' };
              readonly masterCategory: { readonly bsonType: 'string' };
              readonly subCategory: { readonly bsonType: 'string' };
              readonly articleType: { readonly bsonType: 'string' };
              readonly price: {
                readonly bsonType: 'object';
                readonly properties: { readonly currency: { readonly bsonType: 'string' } };
                readonly required: readonly ['currency'];
              };
              readonly image: {
                readonly bsonType: 'object';
                readonly properties: { readonly url: { readonly bsonType: 'string' } };
                readonly required: readonly ['url'];
              };
            };
            readonly required: readonly [
              '_id',
              'articleType',
              'brand',
              'code',
              'description',
              'image',
              'masterCategory',
              'name',
              'price',
              'subCategory',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly users: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
            readonly unique: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly name: { readonly bsonType: 'string' };
              readonly email: { readonly bsonType: 'string' };
              readonly address: {
                readonly oneOf: readonly [
                  { readonly bsonType: 'null' },
                  {
                    readonly bsonType: 'object';
                    readonly properties: {
                      readonly streetAndNumber: { readonly bsonType: 'string' };
                      readonly city: { readonly bsonType: 'string' };
                      readonly postalCode: { readonly bsonType: 'string' };
                      readonly country: { readonly bsonType: 'string' };
                    };
                    readonly required: readonly [
                      'city',
                      'country',
                      'postalCode',
                      'streetAndNumber',
                    ];
                  },
                ];
              };
            };
            readonly required: readonly ['_id', 'email', 'name'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly carts: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [{ readonly field: 'userId'; readonly direction: 1 }];
            readonly unique: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly userId: { readonly bsonType: 'objectId' };
              readonly items: {
                readonly bsonType: 'array';
                readonly items: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly productId: { readonly bsonType: 'string' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly brand: { readonly bsonType: 'string' };
                    readonly amount: { readonly bsonType: 'int' };
                    readonly price: {
                      readonly bsonType: 'object';
                      readonly properties: { readonly currency: { readonly bsonType: 'string' } };
                      readonly required: readonly ['currency'];
                    };
                    readonly image: {
                      readonly bsonType: 'object';
                      readonly properties: { readonly url: { readonly bsonType: 'string' } };
                      readonly required: readonly ['url'];
                    };
                  };
                  readonly required: readonly [
                    'amount',
                    'brand',
                    'image',
                    'name',
                    'price',
                    'productId',
                  ];
                };
              };
            };
            readonly required: readonly ['_id', 'items', 'userId'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly orders: {
        readonly indexes: readonly [
          { readonly keys: readonly [{ readonly field: 'userId'; readonly direction: 1 }] },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly userId: { readonly bsonType: 'objectId' };
              readonly items: {
                readonly bsonType: 'array';
                readonly items: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly productId: { readonly bsonType: 'string' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly brand: { readonly bsonType: 'string' };
                    readonly amount: { readonly bsonType: 'int' };
                    readonly price: {
                      readonly bsonType: 'object';
                      readonly properties: { readonly currency: { readonly bsonType: 'string' } };
                      readonly required: readonly ['currency'];
                    };
                    readonly image: {
                      readonly bsonType: 'object';
                      readonly properties: { readonly url: { readonly bsonType: 'string' } };
                      readonly required: readonly ['url'];
                    };
                  };
                  readonly required: readonly [
                    'amount',
                    'brand',
                    'image',
                    'name',
                    'price',
                    'productId',
                  ];
                };
              };
              readonly shippingAddress: { readonly bsonType: 'string' };
              readonly type: { readonly bsonType: 'string' };
              readonly statusHistory: {
                readonly bsonType: 'array';
                readonly items: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly status: { readonly bsonType: 'string' };
                    readonly timestamp: { readonly bsonType: 'date' };
                  };
                  readonly required: readonly ['status', 'timestamp'];
                };
              };
            };
            readonly required: readonly [
              '_id',
              'items',
              'shippingAddress',
              'statusHistory',
              'type',
              'userId',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly locations: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [
              { readonly field: 'city'; readonly direction: 1 },
              { readonly field: 'country'; readonly direction: 1 },
            ];
            readonly collation: { readonly locale: 'en'; readonly strength: 2 };
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly name: { readonly bsonType: 'string' };
              readonly streetAndNumber: { readonly bsonType: 'string' };
              readonly city: { readonly bsonType: 'string' };
              readonly postalCode: { readonly bsonType: 'string' };
              readonly country: { readonly bsonType: 'string' };
            };
            readonly required: readonly [
              '_id',
              'city',
              'country',
              'name',
              'postalCode',
              'streetAndNumber',
            ];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly invoices: {
        readonly indexes: readonly [
          { readonly keys: readonly [{ readonly field: 'orderId'; readonly direction: 1 }] },
          {
            readonly keys: readonly [{ readonly field: 'issuedAt'; readonly direction: -1 }];
            readonly sparse: true;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly orderId: { readonly bsonType: 'objectId' };
              readonly items: {
                readonly bsonType: 'array';
                readonly items: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly name: { readonly bsonType: 'string' };
                    readonly amount: { readonly bsonType: 'int' };
                  };
                  readonly required: readonly ['amount', 'name'];
                };
              };
              readonly issuedAt: { readonly bsonType: 'date' };
            };
            readonly required: readonly ['_id', 'issuedAt', 'items', 'orderId'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly events: {
        readonly indexes: readonly [
          {
            readonly keys: readonly [
              { readonly field: 'userId'; readonly direction: 1 },
              { readonly field: 'timestamp'; readonly direction: -1 },
            ];
          },
          {
            readonly keys: readonly [{ readonly field: 'timestamp'; readonly direction: 1 }];
            readonly expireAfterSeconds: 7776000;
          },
        ];
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly _id: { readonly bsonType: 'objectId' };
              readonly userId: { readonly bsonType: 'string' };
              readonly sessionId: { readonly bsonType: 'string' };
              readonly type: { readonly bsonType: 'string' };
              readonly timestamp: { readonly bsonType: 'date' };
            };
            readonly required: readonly ['_id', 'sessionId', 'timestamp', 'type', 'userId'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly viewProductEvent: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly productId: { readonly bsonType: 'string' };
              readonly subCategory: { readonly bsonType: 'string' };
              readonly brand: { readonly bsonType: 'string' };
              readonly exitMethod: { readonly bsonType: readonly ['null', 'string'] };
            };
            readonly required: readonly ['brand', 'productId', 'subCategory'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly searchEvent: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: { readonly query: { readonly bsonType: 'string' } };
            readonly required: readonly ['query'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
      readonly addToCartEvent: {
        readonly validator: {
          readonly jsonSchema: {
            readonly bsonType: 'object';
            readonly properties: {
              readonly productId: { readonly bsonType: 'string' };
              readonly brand: { readonly bsonType: 'string' };
            };
            readonly required: readonly ['brand', 'productId'];
          };
          readonly validationLevel: 'strict';
          readonly validationAction: 'error';
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly AddToCartEvent: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly base: 'Event';
    };
    readonly Cart: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly items: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'CartItem' };
          readonly many: true;
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'carts' };
    };
    readonly Event: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly sessionId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly type: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly timestamp: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly discriminator: { readonly field: 'type' };
      readonly variants: {
        readonly ViewProductEvent: { readonly value: 'view-product' };
        readonly SearchEvent: { readonly value: 'search' };
        readonly AddToCartEvent: { readonly value: 'add-to-cart' };
      };
    };
    readonly Invoice: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly orderId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly items: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'InvoiceLineItem' };
          readonly many: true;
        };
        readonly subtotal: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly tax: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly total: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly issuedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
      readonly relations: {
        readonly order: {
          readonly to: 'Order';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['orderId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'invoices' };
    };
    readonly Location: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly streetAndNumber: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'locations' };
    };
    readonly Order: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly items: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'OrderLineItem' };
          readonly many: true;
        };
        readonly shippingAddress: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly type: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly statusHistory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'StatusEntry' };
          readonly many: true;
        };
      };
      readonly relations: {
        readonly user: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['userId'];
            readonly targetFields: readonly ['_id'];
          };
        };
        readonly invoices: {
          readonly to: 'Invoice';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['orderId'];
          };
        };
      };
      readonly storage: { readonly collection: 'orders' };
    };
    readonly Product: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly code: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly description: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly masterCategory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly subCategory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly articleType: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
        readonly embedding: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
          readonly many: true;
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'products' };
    };
    readonly SearchEvent: {
      readonly fields: {
        readonly query: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly base: 'Event';
    };
    readonly User: {
      readonly fields: {
        readonly _id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly address: {
          readonly nullable: true;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Address' };
        };
      };
      readonly relations: {
        readonly carts: {
          readonly to: 'Cart';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['userId'];
          };
        };
        readonly orders: {
          readonly to: 'Order';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['userId'];
          };
        };
      };
      readonly storage: { readonly collection: 'users' };
    };
    readonly ViewProductEvent: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly subCategory: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly exitMethod: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: { readonly collection: 'events' };
      readonly base: 'Event';
    };
  }
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly products: 'Product';
    readonly users: 'User';
    readonly carts: 'Cart';
    readonly orders: 'Order';
    readonly locations: 'Location';
    readonly invoices: 'Invoice';
    readonly events: 'Event';
  };
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly Price: {
      readonly fields: {
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly currency: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly Image: {
      readonly fields: {
        readonly url: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly Address: {
      readonly fields: {
        readonly streetAndNumber: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly city: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly postalCode: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly country: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
      };
    };
    readonly CartItem: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
      };
    };
    readonly OrderLineItem: {
      readonly fields: {
        readonly productId: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly brand: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly price: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Price' };
        };
        readonly image: {
          readonly nullable: false;
          readonly type: { readonly kind: 'valueObject'; readonly name: 'Image' };
        };
      };
    };
    readonly StatusEntry: {
      readonly fields: {
        readonly status: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly timestamp: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
    };
    readonly InvoiceLineItem: {
      readonly fields: {
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly amount: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly unitPrice: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly lineTotal: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
