export type {
  AddColumnDescriptor,
  AddForeignKeyDescriptor,
  AddPrimaryKeyDescriptor,
  AddUniqueDescriptor,
  AlterColumnTypeDescriptor,
  ColumnSpec,
  CreateIndexDescriptor,
  CreateTableDescriptor,
  CreateTypeDescriptor,
  DataTransformDescriptor,
  DropColumnDescriptor,
  DropConstraintDescriptor,
  DropDefaultDescriptor,
  DropIndexDescriptor,
  DropNotNullDescriptor,
  DropTableDescriptor,
  MigrationOpDescriptor,
  SetDefaultDescriptor,
  SetNotNullDescriptor,
} from '../core/migrations/operation-descriptors';
export {
  addColumn,
  addForeignKey,
  addPrimaryKey,
  addUnique,
  alterColumnType,
  createIndex,
  createTable,
  createType,
  dataTransform,
  dropColumn,
  dropConstraint,
  dropDefault,
  dropIndex,
  dropNotNull,
  dropTable,
  setDefault,
  setNotNull,
} from '../core/migrations/operation-descriptors';
