// Re-export everything from the local operation-descriptors module,
// which itself re-exports structural descriptors from sql-family
// and adds postgres-specific data transform support.
export {
  type AddColumnDescriptor,
  type AddEnumValuesDescriptor,
  type AddForeignKeyDescriptor,
  type AddPrimaryKeyDescriptor,
  type AddUniqueDescriptor,
  type AlterColumnTypeDescriptor,
  addColumn,
  addEnumValues,
  addForeignKey,
  addPrimaryKey,
  addUnique,
  alterColumnType,
  type Buildable,
  builders,
  type CreateDependencyDescriptor,
  type CreateEnumTypeDescriptor,
  type CreateIndexDescriptor,
  type CreateTableDescriptor,
  createBuilders,
  createDependency,
  createEnumType,
  createIndex,
  createTable,
  type DataTransformDescriptor,
  type DropColumnDescriptor,
  type DropConstraintDescriptor,
  type DropDefaultDescriptor,
  type DropEnumTypeDescriptor,
  type DropIndexDescriptor,
  type DropNotNullDescriptor,
  type DropTableDescriptor,
  dataTransform,
  dropColumn,
  dropConstraint,
  dropDefault,
  dropEnumType,
  dropIndex,
  dropNotNull,
  dropTable,
  type PostgresMigrationOpDescriptor,
  type QueryPlanInput,
  type RenameTypeDescriptor,
  type RunInput,
  renameType,
  type SetDefaultDescriptor,
  type SetNotNullDescriptor,
  type SqlMigrationOpDescriptor,
  setDefault,
  setNotNull,
  TODO,
  type TodoMarker,
} from '../core/migrations/operation-descriptors';
