export type {
  AddColumnDescriptor,
  AddForeignKeyDescriptor,
  AddPrimaryKeyDescriptor,
  AddUniqueDescriptor,
  AlterColumnTypeDescriptor,
  CreateDependencyDescriptor,
  CreateEnumTypeDescriptor,
  CreateIndexDescriptor,
  CreateTableDescriptor,
  DataTransformDescriptor,
  DropColumnDescriptor,
  DropConstraintDescriptor,
  DropDefaultDescriptor,
  DropIndexDescriptor,
  DropNotNullDescriptor,
  DropTableDescriptor,
  MigrationOpDescriptor,
  SetDefaultDescriptor,
  SetNotNullDescriptor,
} from '../core/migrations/operation-descriptors';
export {
  addColumn,
  addForeignKey,
  addPrimaryKey,
  addUnique,
  alterColumnType,
  builders,
  createDependency,
  createEnumType,
  createIndex,
  createTable,
  dataTransform,
  dropColumn,
  dropConstraint,
  dropDefault,
  dropIndex,
  dropNotNull,
  dropTable,
  setDefault,
  setNotNull,
} from '../core/migrations/operation-descriptors';
