// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type { CodecTypes as CipherstashTypes } from '@prisma-next/extension-cipherstash/codec-types';
import type { QueryOperationTypes as CipherstashQueryOperationTypes } from '@prisma-next/extension-cipherstash/operation-types';
import type {
  EncryptedBigInt,
  EncryptedBoolean,
  EncryptedDate,
  EncryptedDouble,
  EncryptedJson,
  EncryptedString,
} from '@prisma-next/extension-cipherstash/runtime';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ContractModelsMap,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:54398f094e030822dc6f48fc4d423777a8257e5ead12467a41a074777f9b0bd5'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes & CipherstashTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  CipherstashQueryOperationTypes<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly User: {
    readonly id: CodecTypes['pg/text@1']['output'];
    readonly email: CodecTypes['cipherstash/string@1']['output'];
    readonly salary: CodecTypes['cipherstash/double@1']['output'];
    readonly accountId: CodecTypes['cipherstash/bigint@1']['output'];
    readonly birthday: CodecTypes['cipherstash/date@1']['output'];
    readonly emailVerified: CodecTypes['cipherstash/boolean@1']['output'];
    readonly preferences: CodecTypes['cipherstash/json@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly User: {
    readonly id: CodecTypes['pg/text@1']['input'];
    readonly email: CodecTypes['cipherstash/string@1']['input'];
    readonly salary: CodecTypes['cipherstash/double@1']['input'];
    readonly accountId: CodecTypes['cipherstash/bigint@1']['input'];
    readonly birthday: CodecTypes['cipherstash/date@1']['input'];
    readonly emailVerified: CodecTypes['cipherstash/boolean@1']['input'];
    readonly preferences: CodecTypes['cipherstash/json@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly __unbound__: {
          readonly id: '__unbound__';
          readonly kind: 'sql-namespace';
          readonly tables: {
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'eql_v2_encrypted';
                  readonly codecId: 'cipherstash/string@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly equality: true;
                    readonly freeTextSearch: true;
                    readonly orderAndRange: true;
                  };
                };
                readonly salary: {
                  readonly nativeType: 'eql_v2_encrypted';
                  readonly codecId: 'cipherstash/double@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly equality: true; readonly orderAndRange: true };
                };
                readonly accountid: {
                  readonly nativeType: 'eql_v2_encrypted';
                  readonly codecId: 'cipherstash/bigint@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly equality: true; readonly orderAndRange: true };
                };
                readonly birthday: {
                  readonly nativeType: 'eql_v2_encrypted';
                  readonly codecId: 'cipherstash/date@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly equality: true; readonly orderAndRange: true };
                };
                readonly emailverified: {
                  readonly nativeType: 'eql_v2_encrypted';
                  readonly codecId: 'cipherstash/boolean@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly equality: true };
                };
                readonly preferences: {
                  readonly nativeType: 'eql_v2_encrypted';
                  readonly codecId: 'cipherstash/json@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly searchableJson: true };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly User: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly email: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'cipherstash/string@1';
              readonly typeParams: {
                readonly equality: true;
                readonly freeTextSearch: true;
                readonly orderAndRange: true;
              };
            };
          };
          readonly salary: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'cipherstash/double@1';
              readonly typeParams: { readonly equality: true; readonly orderAndRange: true };
            };
          };
          readonly accountId: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'cipherstash/bigint@1';
              readonly typeParams: { readonly equality: true; readonly orderAndRange: true };
            };
          };
          readonly birthday: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'cipherstash/date@1';
              readonly typeParams: { readonly equality: true; readonly orderAndRange: true };
            };
          };
          readonly emailVerified: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'cipherstash/boolean@1';
              readonly typeParams: { readonly equality: true };
            };
          };
          readonly preferences: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'cipherstash/json@1';
              readonly typeParams: { readonly searchableJson: true };
            };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'users';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly email: { readonly column: 'email' };
            readonly salary: { readonly column: 'salary' };
            readonly accountId: { readonly column: 'accountid' };
            readonly birthday: { readonly column: 'birthday' };
            readonly emailVerified: { readonly column: 'emailverified' };
            readonly preferences: { readonly column: 'preferences' };
          };
        };
      };
    }
  >,
  'roots'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {
    readonly cipherstash: {
      readonly familyId: 'sql';
      readonly id: 'cipherstash';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly codecInstances: readonly [
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/string@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly [
                  'cipherstash:equality',
                  'cipherstash:free-text-search',
                  'cipherstash:order-and-range',
                ];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/double@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/bigint@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/date@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality', 'cipherstash:order-and-range'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/boolean@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:equality'];
              };
            },
            {
              readonly descriptor: {
                readonly codecId: 'cipherstash/json@1';
                readonly factory: unknown;
                readonly isParameterized: false;
                readonly meta: {
                  readonly db: {
                    readonly sql: {
                      readonly postgres: { readonly nativeType: 'eql_v2_encrypted' };
                    };
                  };
                };
                readonly paramsSchema: {
                  readonly '~standard': {
                    readonly validate: unknown;
                    readonly vendor: 'cipherstash';
                    readonly version: 1;
                  };
                };
                readonly renderOutputType: unknown;
                readonly targetTypes: readonly ['eql_v2_encrypted'];
                readonly traits: readonly ['cipherstash:searchable-json'];
              };
            },
          ];
          readonly import: {
            readonly alias: 'CipherstashTypes';
            readonly named: 'CodecTypes';
            readonly package: '@prisma-next/extension-cipherstash/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'EncryptedString';
              readonly named: 'EncryptedString';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedDouble';
              readonly named: 'EncryptedDouble';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedBigInt';
              readonly named: 'EncryptedBigInt';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedDate';
              readonly named: 'EncryptedDate';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedBoolean';
              readonly named: 'EncryptedBoolean';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
            {
              readonly alias: 'EncryptedJson';
              readonly named: 'EncryptedJson';
              readonly package: '@prisma-next/extension-cipherstash/runtime';
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'CipherstashQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@prisma-next/extension-cipherstash/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/string@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/double@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/bigint@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/date@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/boolean@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'eql_v2_encrypted';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/json@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = ContractModelsMap<Contract>;
