// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit

import type { MongoContractWithTypeMaps, MongoTypeMaps } from '@prisma-next/mongo-core';
import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:48856eceb7cdcd14bb744daba01f8c089d9f1ff7d3e440094f5930b063687867'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:0b8d49abdbb2759f038452a3b819f0a7db079ffd738c6427562a52064c5327ba'>;

export type CodecTypes = {
  readonly 'mongo/objectId@1': { readonly input: string; readonly output: string };
  readonly 'mongo/string@1': { readonly input: string; readonly output: string };
  readonly 'mongo/int32@1': { readonly input: number; readonly output: number };
  readonly 'mongo/int64@1': { readonly input: bigint; readonly output: bigint };
  readonly 'mongo/double@1': { readonly input: number; readonly output: number };
  readonly 'mongo/bool@1': { readonly input: boolean; readonly output: boolean };
  readonly 'mongo/date@1': { readonly input: Date; readonly output: Date };
  readonly 'mongo/binary@1': { readonly input: Uint8Array; readonly output: Uint8Array };
};
export type OperationTypes = Record<string, never>;
export type TypeMaps = MongoTypeMaps<CodecTypes, OperationTypes>;

type ContractBase = {
  readonly schemaVersion: '1';
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly storageHash: StorageHash;
  readonly executionHash?: ExecutionHash;
  readonly profileHash: ProfileHash;
  readonly capabilities: {};
  readonly extensionPacks: {};
  readonly meta: {};
  readonly sources: {};
  readonly roots: { readonly users: 'User'; readonly posts: 'Post' };
  readonly models: {
    readonly User: {
      readonly fields: {
        readonly _id: { readonly codecId: 'mongo/objectId@1'; readonly nullable: false };
        readonly name: { readonly codecId: 'mongo/string@1'; readonly nullable: false };
        readonly email: { readonly codecId: 'mongo/string@1'; readonly nullable: false };
        readonly bio: { readonly codecId: 'mongo/string@1'; readonly nullable: true };
      };
      readonly relations: {
        readonly posts: {
          readonly to: 'Post';
          readonly cardinality: '1:N';
          readonly on: {
            readonly localFields: readonly ['_id'];
            readonly targetFields: readonly ['authorId'];
          };
        };
      };
      readonly storage: { readonly collection: 'users' };
    };
    readonly Post: {
      readonly fields: {
        readonly _id: { readonly codecId: 'mongo/objectId@1'; readonly nullable: false };
        readonly title: { readonly codecId: 'mongo/string@1'; readonly nullable: false };
        readonly content: { readonly codecId: 'mongo/string@1'; readonly nullable: false };
        readonly authorId: { readonly codecId: 'mongo/objectId@1'; readonly nullable: false };
        readonly createdAt: { readonly codecId: 'mongo/date@1'; readonly nullable: false };
      };
      readonly relations: {
        readonly author: {
          readonly to: 'User';
          readonly cardinality: 'N:1';
          readonly on: {
            readonly localFields: readonly ['authorId'];
            readonly targetFields: readonly ['_id'];
          };
        };
      };
      readonly storage: { readonly collection: 'posts' };
    };
  };
  readonly storage: {
    readonly collections: {
      readonly users: Record<string, never>;
      readonly posts: Record<string, never>;
    };
  };
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
