import { canonicalizeContractToObject } from '@prisma-next/contract/hashing';
import type { Contract } from '@prisma-next/contract/types';
import type { EmissionSpi, ValidationContext } from '@prisma-next/framework-components/emission';
import { ifDefined } from '@prisma-next/utils/defined';
import { format } from 'prettier';
import type { EmitResult, EmitStackInput } from './emit-types';
import { generateContractDts } from './generate-contract-dts';

const SCHEMA_VERSION = '1';

export async function emit(
  contract: Contract,
  stack: EmitStackInput,
  targetFamily: EmissionSpi,
): Promise<EmitResult> {
  const {
    operationRegistry,
    codecTypeImports,
    operationTypeImports,
    extensionIds,
    parameterizedRenderers,
    parameterizedTypeImports,
    queryOperationTypeImports,
  } = stack;

  const ctx: ValidationContext = {
    ...ifDefined('operationRegistry', operationRegistry),
    ...ifDefined('codecTypeImports', codecTypeImports),
    ...ifDefined('operationTypeImports', operationTypeImports),
    ...ifDefined('extensionIds', extensionIds),
  };
  targetFamily.validateTypes(contract, ctx);

  targetFamily.validateStructure(contract);

  const { storageHash } = contract.storage;
  const executionHash = contract.execution?.executionHash;
  const { profileHash } = contract;

  const canonicalized = canonicalizeContractToObject(contract, {
    schemaVersion: SCHEMA_VERSION,
  });
  const contractJsonString = JSON.stringify(
    {
      ...canonicalized,
      _generated: {
        warning: '⚠️  GENERATED FILE - DO NOT EDIT',
        message: 'This file is automatically generated by "prisma-next contract emit".',
        regenerate: 'To regenerate, run: prisma-next contract emit',
      },
    },
    null,
    2,
  );

  const generateOptions =
    parameterizedRenderers || parameterizedTypeImports || queryOperationTypeImports
      ? {
          ...ifDefined('parameterizedRenderers', parameterizedRenderers),
          ...ifDefined('parameterizedTypeImports', parameterizedTypeImports),
          ...ifDefined('queryOperationTypeImports', queryOperationTypeImports),
        }
      : undefined;

  const contractTypeHashes = {
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };
  const contractDtsRaw = generateContractDts(
    contract,
    targetFamily,
    codecTypeImports ?? [],
    operationTypeImports ?? [],
    contractTypeHashes,
    generateOptions,
  );
  const contractDts = await format(contractDtsRaw, {
    parser: 'typescript',
    singleQuote: true,
    semi: true,
    printWidth: 100,
  });

  return {
    contractJson: contractJsonString,
    contractDts,
    storageHash,
    ...ifDefined('executionHash', executionHash),
    profileHash,
  };
}
