import type { Contract, ContractModel, ContractValueObject } from '@prisma-next/contract/types';
import type { CodecLookup } from '@prisma-next/framework-components/codec';
import type {
  EmissionSpi,
  GenerateContractTypesOptions,
  TypesImportSpec,
} from '@prisma-next/framework-components/emission';
import {
  deduplicateImports,
  generateBothFieldTypesMaps,
  generateCodecTypeIntersection,
  generateHashTypeAliases,
  generateImportLines,
  generateModelsType,
  generateRootsType,
  generateValueObjectsDescriptorType,
  generateValueObjectTypeAliases,
  serializeExecutionType,
  serializeValue,
} from './domain-type-generation';

export function generateContractDts(
  contract: Contract,
  emitter: EmissionSpi,
  codecTypeImports: ReadonlyArray<TypesImportSpec>,
  operationTypeImports: ReadonlyArray<TypesImportSpec>,
  hashes: {
    readonly storageHash: string;
    readonly executionHash?: string;
    readonly profileHash: string;
  },
  options?: GenerateContractTypesOptions,
  codecLookup?: CodecLookup,
): string {
  const allImports: TypesImportSpec[] = [...codecTypeImports, ...operationTypeImports];
  if (options?.queryOperationTypeImports) {
    allImports.push(...options.queryOperationTypeImports);
  }
  const uniqueImports = deduplicateImports(allImports);
  const importLines = generateImportLines(uniqueImports);

  const familyImportLines = emitter.getFamilyImports();

  const hashAliases = generateHashTypeAliases(hashes);

  const codecTypes = generateCodecTypeIntersection(codecTypeImports, 'CodecTypes');
  const operationTypes = generateCodecTypeIntersection(operationTypeImports, 'OperationTypes');

  const familyTypeAliases = emitter.getFamilyTypeAliases(options);

  const typeMapsExpr = emitter.getTypeMapsExpression();

  const storageType = emitter.generateStorageType(contract, 'StorageHash');

  const modelsType = generateModelsType(
    contract.models as Record<string, ContractModel>,
    (name, model) => emitter.generateModelStorageType(name, model),
  );

  const rootsType = generateRootsType(contract.roots);

  const valueObjects = contract.valueObjects as Record<string, ContractValueObject> | undefined;
  const valueObjectTypeAliases = generateValueObjectTypeAliases(valueObjects);
  const valueObjectsDescriptor = generateValueObjectsDescriptorType(valueObjects);

  const executionClause =
    contract.execution !== undefined
      ? `\n  readonly execution: ${serializeExecutionType(contract.execution)};`
      : '';

  const fieldTypesMaps = generateBothFieldTypesMaps(
    contract.models as Record<string, ContractModel> | undefined,
    codecLookup,
  );

  const contractWrapper = emitter.getContractWrapper('ContractBase', 'TypeMaps');

  return `// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
${importLines.join('\n')}

${familyImportLines.join('\n')}
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

${hashAliases}

export type CodecTypes = ${codecTypes};
export type OperationTypes = ${operationTypes};
${familyTypeAliases}
${valueObjectTypeAliases}
export type FieldOutputTypes = ${fieldTypesMaps.output};
export type FieldInputTypes = ${fieldTypesMaps.input};
export type TypeMaps = ${typeMapsExpr};

type ContractBase = ContractType<
${storageType},
${modelsType}
> & {
  readonly target: ${serializeValue(contract.target)};
  readonly targetFamily: ${serializeValue(contract.targetFamily)};
  readonly roots: ${rootsType};
  readonly capabilities: ${serializeValue(contract.capabilities)};
  readonly extensionPacks: ${serializeValue(contract.extensionPacks)};${executionClause}
  readonly meta: ${serializeValue(contract.meta)};
  ${valueObjects ? `readonly valueObjects: ${valueObjectsDescriptor};` : ''}
  readonly profileHash: ProfileHash;
};

${contractWrapper}
`;
}
