import type { Contract } from '@prisma-next/contract/types';
import type {
  EmissionSpi,
  GenerateContractTypesOptions,
  TypesImportSpec,
} from '@prisma-next/framework-components/emission';
import {
  deduplicateImports,
  generateCodecTypeIntersection,
  generateHashTypeAliases,
  generateImportLines,
  generateModelsType,
  generateRootsType,
  serializeValue,
} from './domain-type-generation';

export function generateContractDts(
  contract: Contract,
  emitter: EmissionSpi,
  codecTypeImports: ReadonlyArray<TypesImportSpec>,
  operationTypeImports: ReadonlyArray<TypesImportSpec>,
  hashes: {
    readonly storageHash: string;
    readonly executionHash?: string;
    readonly profileHash: string;
  },
  options?: GenerateContractTypesOptions,
): string {
  const allImports: TypesImportSpec[] = [...codecTypeImports, ...operationTypeImports];
  if (options?.parameterizedTypeImports) {
    allImports.push(...options.parameterizedTypeImports);
  }
  if (options?.queryOperationTypeImports) {
    allImports.push(...options.queryOperationTypeImports);
  }
  const uniqueImports = deduplicateImports(allImports);
  const importLines = generateImportLines(uniqueImports);

  const familyImportLines = emitter.getFamilyImports();

  const hashAliases = generateHashTypeAliases(hashes);

  const codecTypes = generateCodecTypeIntersection(codecTypeImports, 'CodecTypes');
  const operationTypes = generateCodecTypeIntersection(operationTypeImports, 'OperationTypes');

  const familyTypeAliases = emitter.getFamilyTypeAliases(options);

  const typeMapsExpr = emitter.getTypeMapsExpression();

  const storageType = emitter.generateStorageType(contract, 'StorageHash');

  const modelsType = emitter.generateModelsType
    ? emitter.generateModelsType(contract, options)
    : generateModelsType(contract.models, (name, model) =>
        emitter.generateModelStorageType(name, model),
      );

  const rootsType = generateRootsType(contract.roots);

  const executionClause =
    contract.execution !== undefined
      ? `\n  readonly execution: ${serializeValue(contract.execution)};`
      : '';

  const contractWrapper = emitter.getContractWrapper('ContractBase', 'TypeMaps');

  return `// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
${importLines.join('\n')}

${familyImportLines.join('\n')}
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

${hashAliases}

export type CodecTypes = ${codecTypes};
export type OperationTypes = ${operationTypes};
${familyTypeAliases}
export type TypeMaps = ${typeMapsExpr};

type ContractBase = ContractType<
${storageType},
${modelsType}
> & {
  readonly target: ${serializeValue(contract.target)};
  readonly roots: ${rootsType};
  readonly capabilities: ${serializeValue(contract.capabilities)};
  readonly extensionPacks: ${serializeValue(contract.extensionPacks)};${executionClause}
  readonly profileHash: ProfileHash;
};

${contractWrapper}
`;
}
