// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/target-postgres/codec-types';
import type { JsonValue } from '@prisma-next/target-postgres/codec-types';
import type { Char } from '@prisma-next/target-postgres/codec-types';
import type { Varchar } from '@prisma-next/target-postgres/codec-types';
import type { Numeric } from '@prisma-next/target-postgres/codec-types';
import type { Bit } from '@prisma-next/target-postgres/codec-types';
import type { VarBit } from '@prisma-next/target-postgres/codec-types';
import type { Timestamp } from '@prisma-next/target-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/target-postgres/codec-types';
import type { Time } from '@prisma-next/target-postgres/codec-types';
import type { Timetz } from '@prisma-next/target-postgres/codec-types';
import type { Interval } from '@prisma-next/target-postgres/codec-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:fe91b8eca8cca26d430660e7659b53f9db1dfb6601a0b74b111460b6bf53940c'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:c6c3cea5c2b12ac00338b4b921ca0f7d8586d278e3bd3ca07b857198ab4c6563'>;
export type ProfileHash =
  ProfileHashBase<'sha256:8329c21fc617189c08798ddf93d0e82a90f7ac26771bb561e41a3f5f622511ff'>;

export type CodecTypes = PgTypes;
export type OperationTypes = Record<string, never>;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Profile: {
    readonly id: Char<36>;
    readonly email: CodecTypes['pg/text@1']['output'];
    readonly displayName: CodecTypes['pg/text@1']['output'] | null;
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly PublicMessage: {
    readonly id: Char<36>;
    readonly authorId: Char<36>;
    readonly body: CodecTypes['pg/text@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
  readonly Todo: {
    readonly id: Char<36>;
    readonly userId: Char<36>;
    readonly title: CodecTypes['pg/text@1']['output'];
    readonly completed: CodecTypes['pg/bool@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Profile: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly email: CodecTypes['pg/text@1']['input'];
    readonly displayName: CodecTypes['pg/text@1']['input'] | null;
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly PublicMessage: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly authorId: CodecTypes['sql/char@1']['input'];
    readonly body: CodecTypes['pg/text@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
  readonly Todo: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly userId: CodecTypes['sql/char@1']['input'];
    readonly title: CodecTypes['pg/text@1']['input'];
    readonly completed: CodecTypes['pg/bool@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  OperationTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly tables: {
      readonly profiles: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly email: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly display_name: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: true;
          };
          readonly created_at: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly public_messages: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly author_id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly body: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly created_at: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
      readonly todos: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly user_id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
            readonly typeParams: { readonly length: 36 };
          };
          readonly title: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly completed: {
            readonly nativeType: 'bool';
            readonly codecId: 'pg/bool@1';
            readonly nullable: false;
          };
          readonly created_at: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
    readonly storageHash: StorageHash;
  },
  {
    readonly Profile: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly email: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly displayName: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'profiles';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly email: { readonly column: 'email' };
          readonly displayName: { readonly column: 'display_name' };
          readonly createdAt: { readonly column: 'created_at' };
        };
      };
    };
    readonly PublicMessage: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly authorId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly body: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'public_messages';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly authorId: { readonly column: 'author_id' };
          readonly body: { readonly column: 'body' };
          readonly createdAt: { readonly column: 'created_at' };
        };
      };
    };
    readonly Todo: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly userId: {
          readonly nullable: false;
          readonly type: {
            readonly kind: 'scalar';
            readonly codecId: 'sql/char@1';
            readonly typeParams: { readonly length: 36 };
          };
        };
        readonly title: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly completed: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'todos';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly userId: { readonly column: 'user_id' };
          readonly title: { readonly column: 'title' };
          readonly completed: { readonly column: 'completed' };
          readonly createdAt: { readonly column: 'created_at' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly profiles: 'Profile';
    readonly todos: 'Todo';
    readonly public_messages: 'PublicMessage';
  };
  readonly capabilities: {
    readonly postgres: {
      readonly 'defaults.now': true;
      readonly 'defaults.uuidv4': true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'public_messages'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: { readonly table: 'todos'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
