// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { JsonValue } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';

import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type StorageHash =
  StorageHashBase<'sha256:380053a4aa786e23a6bbe0a8631cbed15794cfebc505920716ca3f14e1df8bf8'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:38ad0324652b295263d61fa58c7da16c0d1a4d32d6c06370ddb198e857a8468c'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9968c4a694e9d0bd70b959b5434f49cc8bd17deb1e4441dda4b41d13352839ab'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly zod_event: {
        columns: {
          readonly id: {
            readonly nativeType: 'character';
            readonly codecId: 'sql/char@1';
            readonly nullable: false;
          };
          readonly event: {
            readonly nativeType: 'jsonb';
            readonly codecId: 'pg/jsonb@1';
            readonly nullable: false;
          };
          readonly source: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
          readonly created_at: {
            readonly nativeType: 'timestamptz';
            readonly codecId: 'pg/timestamptz@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly ZodEvent: {
      storage: { readonly table: 'zod_event' };
      fields: {
        readonly id: Char<26>;
        readonly source: CodecTypes['pg/text@1']['output'];
        readonly event:
          | { _tag: 'user.created'; email: string; userId: string }
          | { _tag: 'post.published'; authorId: string; postId: string }
          | { _tag: 'payment.captured'; amountCents: number; paymentId: string };
        readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: { readonly ZodEvent: 'zod_event' };
    tableToModel: { readonly zod_event: 'ZodEvent' };
    fieldToColumn: {
      readonly ZodEvent: {
        readonly id: 'id';
        readonly source: 'source';
        readonly event: 'event';
        readonly createdAt: 'created_at';
      };
    };
    columnToField: {
      readonly zod_event: {
        readonly id: 'id';
        readonly source: 'source';
        readonly event: 'event';
        readonly created_at: 'createdAt';
      };
    };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  },
  StorageHash,
  ExecutionHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
