export type {
  AuthoringArgRef,
  AuthoringArgumentDescriptor,
  AuthoringColumnDefaultTemplate,
  AuthoringContributions,
  AuthoringEntityContext,
  AuthoringEntityDescriptor,
  AuthoringEntityFactoryOutput,
  AuthoringEntityNamespace,
  AuthoringEntityTemplateOutput,
  AuthoringFieldNamespace,
  AuthoringFieldPresetDescriptor,
  AuthoringFieldPresetOutput,
  AuthoringStorageTypeTemplate,
  AuthoringTemplateValue,
  AuthoringTypeConstructorDescriptor,
  AuthoringTypeNamespace,
} from '../shared/framework-authoring';
export {
  assertNoCrossRegistryCollisions,
  hasRegisteredFieldNamespace,
  instantiateAuthoringEntity,
  instantiateAuthoringFieldPreset,
  instantiateAuthoringTypeConstructor,
  isAuthoringArgRef,
  isAuthoringEntityDescriptor,
  isAuthoringFieldPresetDescriptor,
  isAuthoringTypeConstructorDescriptor,
  mergeAuthoringNamespaces,
  resolveAuthoringTemplateValue,
  validateAuthoringHelperArguments,
} from '../shared/framework-authoring';
