export type {
  AdapterDescriptor,
  AdapterInstance,
  AdapterPackRef,
  ComponentDescriptor,
  ComponentMetadata,
  ContractComponentRequirementsCheckInput,
  ContractComponentRequirementsCheckResult,
  DriverDescriptor,
  DriverInstance,
  DriverPackRef,
  ExtensionDescriptor,
  ExtensionInstance,
  ExtensionPackRef,
  FamilyDescriptor,
  FamilyInstance,
  FamilyPackRef,
  PackRefBase,
  TargetBoundComponentDescriptor,
  TargetDescriptor,
  TargetInstance,
  TargetPackRef,
} from '../shared/framework-components';
export { checkContractComponentRequirements } from '../shared/framework-components';
